import { createClient } from "jsr:@supabase/supabase-js@2.112.4";
import { buildCorsHeaders } from "../_shared/cors.ts";
import { getEmailProvider } from "../_shared/email/index.ts";
import { sendSecurityAlert } from "../_shared/securityAlert.ts";
import { timingSafeEqual } from "../_shared/timingSafeEqual.ts";

// Emails a platform invoice (EduCore -> school) with the official PDF attached.
//
// The PDF is generated by the Next.js app (src/lib/billing/invoice-pdf.ts) and passed in as
// base64, so there is exactly ONE invoice layout in the codebase.
//
// Auth (verify_jwt is false for this function -- see config.toml -- and the check is done here):
//   * an administrator's own JWT (the "Send invoice" button), verified with auth_is_super_admin; or
//   * the shared x-dispatch-secret (DISPATCH_SECRET) used by the billing cron when auto_send is on,
//     the same server-to-server mechanism send-communication uses because the gateway mishandles
//     sb_secret_ keys in Authorization.
//
// Safety:
//   * Refuses to run if Resend is not configured. getEmailProvider() would otherwise silently fall
//     back to a console logger and we would record an invoice as "sent" that never left the building.
//   * An invoice is only marked sent AFTER the provider accepted the message.
//   * An invoice that was already sent is not re-sent unless the admin explicitly passes resend=true,
//     so a retried cron or double-click cannot email a school the same invoice twice.
//   * Drafts and cancelled invoices are never sent.

const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
const MAX_PDF_BASE64_CHARS = 4_000_000; // ~3 MB of PDF

const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string);

const kes = (n: number) =>
  `KES ${Number(n).toLocaleString("en-KE", { minimumFractionDigits: Number.isInteger(Number(n)) ? 0 : 2, maximumFractionDigits: 2 })}`;

const nairobiDate = (iso: string) =>
  new Intl.DateTimeFormat("en-GB", { timeZone: "Africa/Nairobi", day: "2-digit", month: "short", year: "numeric" }).format(new Date(iso));

Deno.serve(async (req) => {
  const corsHeaders = buildCorsHeaders(req);
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  let invoiceId: string | undefined;
  const serviceClient = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

  try {
    // ---- authenticate ------------------------------------------------------------------
    const dispatchSecret = Deno.env.get("DISPATCH_SECRET");
    const providedSecret = req.headers.get("x-dispatch-secret");
    const isDispatchCaller = !!dispatchSecret && !!providedSecret && timingSafeEqual(providedSecret, dispatchSecret);
    let isAdminCaller = false;
    if (!isDispatchCaller) {
      const authHeader = req.headers.get("Authorization");
      if (!authHeader) return json({ error: "Missing Authorization header." }, 401);
      const userClient = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_ANON_KEY")!, {
        global: { headers: { Authorization: authHeader } },
      });
      const { data: isSuperAdmin } = await userClient.rpc("auth_is_super_admin");
      if (isSuperAdmin !== true) return json({ error: "Not authorized." }, 403);
      isAdminCaller = true;
    }

    // ---- validate input ----------------------------------------------------------------
    let body: { invoice_id?: string; pdf_base64?: string; to?: string; resend?: boolean };
    try {
      body = await req.json();
    } catch {
      return json({ error: "Invalid JSON body" }, 400);
    }
    invoiceId = body.invoice_id;
    if (!invoiceId) return json({ error: "invoice_id is required" }, 400);
    const pdf = body.pdf_base64;
    if (!pdf || typeof pdf !== "string") return json({ error: "pdf_base64 is required" }, 400);
    if (pdf.length > MAX_PDF_BASE64_CHARS) return json({ error: "PDF is too large to email." }, 413);
    if (!pdf.startsWith("JVBERi")) return json({ error: "Attachment is not a PDF." }, 400); // base64 of "%PDF-"
    // Only a signed-in administrator may redirect an invoice to an arbitrary address / force a resend.
    const toOverride = isAdminCaller && body.to ? body.to.trim() : null;
    if (toOverride && !EMAIL_RE.test(toOverride)) return json({ error: "That recipient email address is not valid." }, 400);
    const resend = isAdminCaller && body.resend === true;

    // Real provider only (see header comment).
    if (!Deno.env.get("RESEND_API_KEY") || !Deno.env.get("RESEND_FROM_ADDRESS")) {
      return json({ error: "Email delivery is not configured (RESEND_API_KEY / RESEND_FROM_ADDRESS). The invoice was NOT sent." }, 503);
    }

    // ---- load invoice + recipient --------------------------------------------------------
    const { data: inv, error: invErr } = await serviceClient
      .from("platform_invoices")
      .select("id, school_id, invoice_number, status, billing_period_label, student_count, unit_price_kes, amount_kes, amount_paid_kes, due_at, sent_at, bill_to")
      .eq("id", invoiceId)
      .maybeSingle();
    if (invErr || !inv) return json({ error: "Invoice not found." }, 404);
    if (inv.status === "draft" || inv.status === "cancelled") return json({ error: `A ${inv.status} invoice cannot be emailed.` }, 409);
    if (inv.sent_at && !resend) {
      return json({ error: `This invoice was already emailed on ${nairobiDate(inv.sent_at)}. Use “Resend” to send it again.` }, 409);
    }

    const { data: sub } = await serviceClient.from("school_subscriptions").select("billing_email").eq("school_id", inv.school_id).maybeSingle();
    const { data: ownerRole } = await serviceClient.from("roles").select("id").eq("name", "school_owner").maybeSingle();
    const { data: owner } = ownerRole
      ? await serviceClient
          .from("school_users")
          .select("email, full_name")
          .eq("school_id", inv.school_id)
          .eq("role_id", ownerRole.id)
          .eq("status", "active")
          .not("email", "is", null)
          .limit(1)
          .maybeSingle()
      : { data: null };
    const { data: school } = await serviceClient.from("schools").select("name, email").eq("id", inv.school_id).maybeSingle();

    // Recipient priority: explicit admin override > configured billing email > school owner > school contact email.
    const recipient = [toOverride, sub?.billing_email, owner?.email, school?.email, (inv.bill_to as { email?: string } | null)?.email]
      .map((v) => (v ?? "").trim())
      .find((v) => EMAIL_RE.test(v));
    if (!recipient) {
      return json({ error: "No billing email on file. Set one on the invoice page, or add an owner email for this school." }, 422);
    }

    // ---- compose -------------------------------------------------------------------------
    const schoolName = (inv.bill_to as { name?: string } | null)?.name ?? school?.name ?? "your school";
    const subject = `EduCore Invoice ${inv.invoice_number} — ${schoolName}`;
    const balance = Number(inv.amount_kes) - Number(inv.amount_paid_kes ?? 0);
    const greeting = owner?.full_name && recipient === owner.email ? `Dear ${owner.full_name},` : "Dear Sir/Madam,";
    const rows: [string, string][] = [
      ["Invoice number", inv.invoice_number],
      ["Billing period", inv.billing_period_label ?? "—"],
      ["Students billed", String(inv.student_count)],
      ["Amount due", kes(balance)],
      ["Due date", nairobiDate(inv.due_at)],
    ];
    const text = [
      greeting,
      "",
      `Please find attached invoice ${inv.invoice_number} for ${schoolName} (${inv.billing_period_label ?? "subscription"}).`,
      "",
      ...rows.map(([k, v]) => `${k}: ${v}`),
      "",
      "Payment instructions are shown on the attached invoice. If you have already paid, please reply with the payment reference.",
      "",
      "Kind regards,",
      "EduCore Africa",
      "info@educoreafrica.com | +254 702 904 562 | educoreafrica.com",
    ].join("\n");
    const html = `<div style="font-family:Inter,Arial,sans-serif;font-size:14px;line-height:1.55;color:#0A1730;max-width:560px">
<p>${esc(greeting)}</p>
<p>Please find attached invoice <strong>${esc(inv.invoice_number)}</strong> for ${esc(schoolName)} (${esc(inv.billing_period_label ?? "subscription")}).</p>
<table style="border-collapse:collapse;margin:12px 0;font-size:14px">${rows
      .map(([k, v]) => `<tr><td style="padding:3px 18px 3px 0;color:#545D6E">${esc(k)}</td><td style="padding:3px 0;font-weight:600">${esc(v)}</td></tr>`)
      .join("")}</table>
<p>Payment instructions are shown on the attached invoice. If you have already paid, please reply with the payment reference.</p>
<p style="margin-top:20px">Kind regards,<br><strong>EduCore Africa</strong><br><span style="color:#545D6E">info@educoreafrica.com · +254 702 904 562 · educoreafrica.com</span></p>
</div>`;

    // ---- send, then record -----------------------------------------------------------------
    try {
      await getEmailProvider().send(
        recipient,
        subject,
        text,
        [{ filename: `EduCore-Invoice-${String(inv.invoice_number).replace(/[^A-Za-z0-9-]/g, "")}.pdf`, contentBase64: pdf }],
        undefined,
        { html, replyTo: "info@educoreafrica.com" },
      );
    } catch (sendErr) {
      const message = sendErr instanceof Error ? sendErr.message : String(sendErr);
      await serviceClient.rpc("log_platform_invoice_event", { p_invoice_id: inv.id, p_event_type: "send_failed", p_metadata: { to: recipient, error: message.slice(0, 500) } });
      console.error("send-platform-invoice: provider rejected the message", message);
      return json({ error: "The email provider could not send the invoice. It has NOT been marked as sent." }, 502);
    }

    const { error: markErr } = await serviceClient.rpc("mark_platform_invoice_sent", { p_invoice_id: inv.id, p_sent_to: recipient });
    if (markErr) {
      // The email DID go out; surface the bookkeeping problem loudly rather than pretend it failed.
      console.error("send-platform-invoice: sent, but failed to record it", markErr);
      void sendSecurityAlert("Invoice emailed but not recorded as sent", { invoice_id: inv.id, error: markErr.message });
      return json({ success: true, sent_to: recipient, warning: "Sent, but the sent status could not be recorded." });
    }
    return json({ success: true, sent_to: recipient });
  } catch (err) {
    console.error("send-platform-invoice: unexpected error", err);
    void sendSecurityAlert("Platform invoice email failed unexpectedly", {
      invoice_id: invoiceId ?? "unknown",
      error: err instanceof Error ? err.message : String(err),
    });
    return json({ error: "Unexpected error sending the invoice." }, 500);
  }
});
