-- Part 29. Splits competency_evidence_write (ALL, created in part 17) +
-- competency_evidence_select (SELECT) into 4 explicit per-action policies,
-- resolving the residual ALL+SELECT overlap that part 17 explicitly
-- deferred.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists competency_evidence_write on public.competency_evidence;
drop policy if exists competency_evidence_write_any on public.competency_evidence;
drop policy if exists competency_evidence_write_own on public.competency_evidence;
drop policy if exists competency_evidence_select on public.competency_evidence;
drop policy if exists competency_evidence_insert on public.competency_evidence;
drop policy if exists competency_evidence_update on public.competency_evidence;
drop policy if exists competency_evidence_delete on public.competency_evidence;

create policy competency_evidence_delete on public.competency_evidence
  for DELETE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = competency_evidence.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;

create policy competency_evidence_insert on public.competency_evidence
  for INSERT
  with check (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = competency_evidence.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;

create policy competency_evidence_select on public.competency_evidence
  for SELECT
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = competency_evidence.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))) OR ((( SELECT auth.role() AS role) = 'authenticated'::text) AND (((school_id = auth_school_id()) AND auth_has_permission('exams.read'::text)) OR (EXISTS ( SELECT 1
   FROM competency_marks cm
  WHERE ((cm.id = competency_evidence.competency_mark_id) AND ((auth_user_id_is_guardian_of(cm.student_id) AND (EXISTS ( SELECT 1
           FROM report_cards rc
          WHERE ((rc.exam_id = cm.exam_id) AND (rc.student_id = cm.student_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text])))))) OR ((EXISTS ( SELECT 1
           FROM (students st
             JOIN school_users su ON ((su.id = st.school_user_id)))
          WHERE ((st.id = cm.student_id) AND (su.auth_user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
           FROM report_cards rc
          WHERE ((rc.exam_id = cm.exam_id) AND (rc.student_id = cm.student_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text])))))))))))))
  )
;

create policy competency_evidence_update on public.competency_evidence
  for UPDATE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = competency_evidence.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
with check (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = competency_evidence.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;
