-- Part 35 (last of the RLS consolidation series). Splits
-- rubric_criterion_scores_write (ALL, created in part 23) +
-- rubric_criterion_scores_select (SELECT) into 4 explicit per-action
-- policies, resolving the residual ALL+SELECT overlap that part 23
-- explicitly deferred.
--
-- This is the final table in the series -- after this migration, every
-- table in public with a school_id column and multiple RLS policies for
-- the same action, and every ALL-cmd policy that overlapped with a
-- separate action-specific policy, has been resolved. Confirmed via:
--   select tablename, cmd, count(*) from pg_policies
--   where schemaname='public' and permissive='PERMISSIVE'
--   group by 1,2 having count(*) > 1;
-- returning zero rows against production.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists rubric_criterion_scores_write on public.rubric_criterion_scores;
drop policy if exists rubric_criterion_scores_write_any on public.rubric_criterion_scores;
drop policy if exists rubric_criterion_scores_write_own on public.rubric_criterion_scores;
drop policy if exists rubric_criterion_scores_select on public.rubric_criterion_scores;
drop policy if exists rubric_criterion_scores_insert on public.rubric_criterion_scores;
drop policy if exists rubric_criterion_scores_update on public.rubric_criterion_scores;
drop policy if exists rubric_criterion_scores_delete on public.rubric_criterion_scores;

create policy rubric_criterion_scores_delete on public.rubric_criterion_scores
  for DELETE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = rubric_criterion_scores.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;

create policy rubric_criterion_scores_insert on public.rubric_criterion_scores
  for INSERT
  with check (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = rubric_criterion_scores.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;

create policy rubric_criterion_scores_select on public.rubric_criterion_scores
  for SELECT
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = rubric_criterion_scores.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))) OR ((( SELECT auth.role() AS role) = 'authenticated'::text) AND (((school_id = auth_school_id()) AND auth_has_permission('exams.read'::text)) OR (EXISTS ( SELECT 1
   FROM competency_marks cm
  WHERE ((cm.id = rubric_criterion_scores.competency_mark_id) AND ((auth_user_id_is_guardian_of(cm.student_id) AND (EXISTS ( SELECT 1
           FROM report_cards rc
          WHERE ((rc.exam_id = cm.exam_id) AND (rc.student_id = cm.student_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text])))))) OR ((EXISTS ( SELECT 1
           FROM (students st
             JOIN school_users su ON ((su.id = st.school_user_id)))
          WHERE ((st.id = cm.student_id) AND (su.auth_user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
           FROM report_cards rc
          WHERE ((rc.exam_id = cm.exam_id) AND (rc.student_id = cm.student_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text])))))))))))))
  )
;

create policy rubric_criterion_scores_update on public.rubric_criterion_scores
  for UPDATE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = rubric_criterion_scores.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
with check (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM (((competency_marks cm
     JOIN students st ON ((st.id = cm.student_id)))
     JOIN curriculum_sub_strands css ON ((css.id = cm.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((cm.id = rubric_criterion_scores.competency_mark_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;
