-- Part 34. Splits role_permissions_write (ALL, created in part 22) +
-- role_permissions_select (SELECT) into 4 explicit per-action policies,
-- resolving the residual ALL+SELECT overlap that part 22 explicitly
-- deferred. Extra care again: role_permissions_select's own branch
-- (auth_is_super_admin() OR school_id IS NULL OR school_id = auth_school_id())
-- is deliberately broader than the write policy -- any authenticated staff
-- member can read what permissions a role has, but only
-- settings.roles.manage holders or super_admin can write -- and that
-- asymmetry is preserved exactly as it already existed live.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists role_permissions_write on public.role_permissions;
drop policy if exists role_permissions_override_manage on public.role_permissions;
drop policy if exists role_permissions_write_super_admin on public.role_permissions;
drop policy if exists role_permissions_select on public.role_permissions;
drop policy if exists role_permissions_insert on public.role_permissions;
drop policy if exists role_permissions_update on public.role_permissions;
drop policy if exists role_permissions_delete on public.role_permissions;

create policy role_permissions_delete on public.role_permissions
  for DELETE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('settings.roles.manage'::text)) OR auth_is_super_admin())
  )
;

create policy role_permissions_insert on public.role_permissions
  for INSERT
  with check (
    (((school_id = auth_school_id()) AND auth_has_permission('settings.roles.manage'::text)) OR auth_is_super_admin())
  )
;

create policy role_permissions_select on public.role_permissions
  for SELECT
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('settings.roles.manage'::text)) OR auth_is_super_admin() OR (auth_is_super_admin() OR (school_id IS NULL) OR (school_id = auth_school_id())))
  )
;

create policy role_permissions_update on public.role_permissions
  for UPDATE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('settings.roles.manage'::text)) OR auth_is_super_admin())
  )
with check (
    (((school_id = auth_school_id()) AND auth_has_permission('settings.roles.manage'::text)) OR auth_is_super_admin())
  )
;
