-- ============================================================================
-- Procurement follow-up: three related gaps closed together because the second
-- and third genuinely depend on the first.
--
-- 1. PO numbers were free-text, typed by whoever issued the order (collision-
--    prone, no real meaning). Now generated by the database itself, same
--    pattern already used for receipt numbers (generate_receipt): a sequence
--    plus a human-readable prefix, so it's guaranteed unique and nobody has to
--    invent one.
-- 2. receiveGoodsAction/record_goods_received recorded quantity_received on
--    the PO line but never touched inventory_items.quantity or
--    inventory_stock_movements -- so goods received didn't change stock and
--    someone had to re-key the same quantity through "Adjust Stock"
--    separately. Fixed at the same row-locked, atomic call site used for the
--    quantity_received update, and only for PO lines that are actually linked
--    to a catalog item (inventory_item_id) -- a line for something outside
--    the stock catalog (e.g. a one-off service) has nothing to post to.
-- 3. Nothing watched reorder_level. Now an AFTER UPDATE OF quantity trigger on
--    inventory_items fires the moment stock crosses at/below its reorder
--    level, and (if the item has at least one prior purchase order to base a
--    reorder on) auto-creates a new PO for the same supplier and quantity as
--    the last order, and emails that supplier. The quantity is a normal
--    purchase_order_items.quantity value -- editable via
--    updatePurchaseOrderItemAction like any PO line, so "same as last time"
--    is a starting default, never a locked-in number. Items with no order
--    history yet have nothing to copy from, so procurement staff are notified
--    in-app to raise the first order manually instead of guessing a supplier.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Auto-generated PO numbers
-- ----------------------------------------------------------------------------
create sequence if not exists public.po_number_seq;

alter table public.purchase_orders
  alter column po_number set default ('PO-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.po_number_seq')::text, 5, '0'));

comment on column public.purchase_orders.po_number is
  'Auto-generated (PO-<year>-<sequence>) via column default -- never typed by the issuer. Still a real column (not computed) so a school could override it in an edge case without a schema change.';

-- ----------------------------------------------------------------------------
-- 2. Receiving goods now posts straight to stock, atomically, in the same
-- row-locked function that already updates quantity_received (see
-- 20260818074327_receive_goods_atomic_quantity_update.sql -- this replaces
-- that version, keeping its locking behaviour and adding the stock posting).
-- ----------------------------------------------------------------------------
create or replace function public.record_goods_received(
  p_po_id uuid,
  p_po_item_id uuid,
  p_quantity_received integer
)
returns purchase_order_items
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_school_id uuid := auth_school_id();
  v_actor uuid;
  v_result public.purchase_order_items;
  v_po_number text;
begin
  if not auth_has_permission('inventory.write') then
    raise exception 'insufficient permissions: inventory.write required';
  end if;
  if p_quantity_received <= 0 then
    raise exception 'quantity received must be positive';
  end if;

  select id into v_actor from public.school_users where auth_user_id = auth.uid();

  update public.purchase_order_items
  set quantity_received = quantity_received + p_quantity_received
  where id = p_po_item_id
    and school_id = v_school_id
  returning * into v_result;

  if v_result.id is null then
    raise exception 'purchase order item not found in this school';
  end if;

  update public.purchase_orders
  set status = case when v_result.quantity_received >= v_result.quantity then 'received' else 'partially_received' end,
      updated_at = now()
  where id = p_po_id
    and school_id = v_school_id
  returning po_number into v_po_number;

  -- Post to stock only when this PO line is linked to a catalog item. A line
  -- for something outside the inventory catalog (e.g. a one-off service) has
  -- no inventory_items row to post against, and that's expected, not an error.
  if v_result.inventory_item_id is not null then
    perform 1 from public.inventory_items where id = v_result.inventory_item_id and school_id = v_school_id for update;
    if not found then
      raise exception 'linked inventory item not found in this school';
    end if;

    update public.inventory_items
    set quantity = quantity + p_quantity_received,
        updated_at = now()
    where id = v_result.inventory_item_id
      and school_id = v_school_id;

    insert into public.inventory_stock_movements (school_id, item_id, movement_type, quantity, reason, actor)
    values (v_school_id, v_result.inventory_item_id, 'in', p_quantity_received, 'Goods received: PO ' || coalesce(v_po_number, ''), v_actor);
  end if;

  return v_result;
end;
$$;

-- ----------------------------------------------------------------------------
-- 3. Low-stock auto-reorder + supplier email.
-- ----------------------------------------------------------------------------

-- 3a. Suppliers are an external party, not a school_user -- widen the existing
-- recipient_type check (same pattern as widening the channel check in
-- 20260810064531_phase9_communication_check.sql) rather than adding a
-- parallel table.
alter table public.notification_logs drop constraint notification_logs_recipient_type_check;
alter table public.notification_logs add constraint notification_logs_recipient_type_check check (recipient_type in ('guardian', 'student', 'staff', 'supplier'));

-- 3b. Queues (does not itself dispatch -- same queued/send-communication split
-- as everything else in Communication) one email to a PO's supplier
-- summarising its lines. Split into an internal worker with no permission
-- check (called from the auto-reorder trigger below, which runs as a side
-- effect of a plain stock movement -- the person doing that stock-out may
-- well not hold inventory.procurement.approve, and a permission check there
-- would abort their otherwise-legitimate movement) and a permission-checked
-- wrapper for direct client use (e.g. after createPurchaseOrderAction).
create or replace function public._queue_supplier_po_email(p_po_id uuid, p_school_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_po record;
  v_school_name text;
  v_lines text := '';
  v_item record;
begin
  select po.po_number, po.supplier_id, s.name as supplier_name, s.email as supplier_email
  into v_po
  from public.purchase_orders po
  join public.suppliers s on s.id = po.supplier_id
  where po.id = p_po_id and po.school_id = p_school_id;

  if v_po.po_number is null then
    raise exception 'purchase order not found in this school';
  end if;
  if v_po.supplier_email is null then
    return; -- no email on file for this supplier -- the PO itself is still valid, just nothing to send
  end if;

  select name into v_school_name from public.schools where id = p_school_id;

  for v_item in select item_description, quantity, unit_cost from public.purchase_order_items where po_id = p_po_id loop
    v_lines := v_lines || format(e'\n- %s x %s (unit cost %s)', v_item.quantity, v_item.item_description, coalesce(v_item.unit_cost::text, 'n/a'));
  end loop;

  insert into public.notification_logs (school_id, recipient_email, recipient_phone, recipient_type, channel, subject, body, status, segments)
  values (
    p_school_id,
    v_po.supplier_email,
    '-',
    'supplier',
    'email',
    'Purchase Order ' || v_po.po_number || ' from ' || coalesce(v_school_name, 'us'),
    format(
      e'Dear %s,\n\nPlease find our purchase order %s below:\n%s\n\nKindly confirm and arrange delivery at your earliest convenience.\n\nRegards,\n%s',
      coalesce(v_po.supplier_name, 'Supplier'), v_po.po_number, v_lines, coalesce(v_school_name, 'The School')
    ),
    'queued',
    1
  );
end;
$$;

revoke all on function public._queue_supplier_po_email(uuid, uuid) from public, anon, authenticated;

create or replace function public.queue_supplier_po_email(p_po_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_school_id uuid := auth_school_id();
begin
  if not auth_has_permission('inventory.procurement.approve') then
    raise exception 'insufficient permissions: inventory.procurement.approve required';
  end if;

  perform public._queue_supplier_po_email(p_po_id, v_school_id);
end;
$$;

revoke all on function public.queue_supplier_po_email(uuid) from public, anon;
grant execute on function public.queue_supplier_po_email(uuid) to authenticated;

-- 3c. Fires when stock crosses at/below reorder_level. WHEN clause on the
-- trigger (not just an early-return inside the function) so it doesn't even
-- run on every other quantity change -- and only fires the update that
-- crosses the line, never re-fires on further movements while already below
-- it, matching the same "fire once per streak" shape as
-- check_consecutive_absences().
create or replace function public.trg_auto_reorder_on_low_stock()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_last record;
  v_po_id uuid;
  v_already_open boolean;
begin
  select exists (
    select 1
    from public.purchase_order_items poi
    join public.purchase_orders po on po.id = poi.po_id
    where poi.inventory_item_id = new.id
      and po.status in ('draft', 'sent', 'partially_received')
  ) into v_already_open;
  if v_already_open then
    -- Already an open order out for this item (whether auto- or manually
    -- raised) -- don't pile a second one on top of it.
    return new;
  end if;

  select poi.quantity, poi.unit_cost, po.supplier_id
  into v_last
  from public.purchase_order_items poi
  join public.purchase_orders po on po.id = poi.po_id
  where poi.inventory_item_id = new.id
    and po.school_id = new.school_id
  order by po.order_date desc, po.created_at desc
  limit 1;

  if v_last.supplier_id is null then
    perform public.notify_users_with_permission(
      'inventory.procurement.approve',
      'Low stock: ' || new.name,
      new.name || ' has reached its reorder level (' || new.quantity || ' ' || new.unit || ' left) and has no previous purchase order to reorder from automatically. Please raise a purchase order manually.',
      '/inventory/procurement',
      'other'
    );
    return new;
  end if;

  insert into public.purchase_orders (school_id, supplier_id, status, notes)
  values (
    new.school_id,
    v_last.supplier_id,
    'sent',
    'Auto-generated: ' || new.name || ' reached its reorder level (' || new.quantity || ' ' || new.unit || ' remaining, reorder level ' || new.reorder_level || '). Quantity defaulted to the last order for this item.'
  )
  returning id into v_po_id;

  insert into public.purchase_order_items (po_id, school_id, item_description, quantity, unit_cost, inventory_item_id)
  values (v_po_id, new.school_id, new.name, v_last.quantity, v_last.unit_cost, new.id);

  perform public._queue_supplier_po_email(v_po_id, new.school_id);

  perform public.notify_users_with_permission(
    'inventory.procurement.approve',
    'Auto purchase order raised for ' || new.name,
    new.name || ' hit its reorder level. A purchase order was auto-raised for the same quantity as the last order and the supplier has been emailed. Open it in Procurement if the quantity needs adjusting.',
    '/inventory/procurement',
    'other'
  );

  return new;
end;
$$;

revoke all on function public.trg_auto_reorder_on_low_stock() from public, anon, authenticated;

drop trigger if exists trg_inventory_low_stock_reorder on public.inventory_items;
create trigger trg_inventory_low_stock_reorder
  after update of quantity on public.inventory_items
  for each row
  when (new.reorder_level is not null and new.quantity <= new.reorder_level and (old.quantity is distinct from new.quantity) and (old.quantity > old.reorder_level or old.reorder_level is null))
  execute function public.trg_auto_reorder_on_low_stock();

-- ----------------------------------------------------------------------------
-- 4. Let a PO line's quantity/unit cost be edited after issue (covers both
-- correcting a manually-issued PO and adjusting an auto-raised one before or
-- after the supplier's been emailed) -- but never once goods have started
-- arriving against it, since a received quantity is a fact, not a plan.
-- ----------------------------------------------------------------------------
create or replace function public.update_purchase_order_item(
  p_po_item_id uuid,
  p_quantity numeric,
  p_unit_cost numeric
)
returns public.purchase_order_items
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_school_id uuid := auth_school_id();
  v_result public.purchase_order_items;
begin
  if not auth_has_permission('inventory.procurement.approve') then
    raise exception 'insufficient permissions: inventory.procurement.approve required';
  end if;
  if p_quantity <= 0 then
    raise exception 'quantity must be positive';
  end if;

  update public.purchase_order_items
  set quantity = p_quantity,
      unit_cost = coalesce(p_unit_cost, unit_cost)
  where id = p_po_item_id
    and school_id = v_school_id
    and quantity_received = 0
  returning * into v_result;

  if v_result.id is null then
    raise exception 'purchase order item not found, not in this school, or already has goods received against it';
  end if;

  return v_result;
end;
$$;

revoke all on function public.update_purchase_order_item(uuid, numeric, numeric) from public, anon;
grant execute on function public.update_purchase_order_item(uuid, numeric, numeric) to authenticated;
