-- Part 28. Split subject_catalogue_super_admin_write (ALL) +
-- subject_catalogue_select (SELECT) into 4 explicit per-action policies --
-- same ALL+SELECT overlap reasoning as part 24. subject_catalogue_select's
-- qual is a plain `true` (readable by any authenticated user -- it's a
-- global reference table of subject names, not per-tenant data), preserved
-- unchanged.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists subject_catalogue_super_admin_write on public.subject_catalogue;
drop policy if exists subject_catalogue_select on public.subject_catalogue;
drop policy if exists subject_catalogue_insert on public.subject_catalogue;
drop policy if exists subject_catalogue_update on public.subject_catalogue;
drop policy if exists subject_catalogue_delete on public.subject_catalogue;

create policy subject_catalogue_delete on public.subject_catalogue
  for DELETE
  using (
    auth_is_super_admin()
  )
;

create policy subject_catalogue_insert on public.subject_catalogue
  for INSERT
  with check (
    auth_is_super_admin()
  )
;

create policy subject_catalogue_select on public.subject_catalogue
  for SELECT
  using (
    (auth_is_super_admin() OR true)
  )
;

create policy subject_catalogue_update on public.subject_catalogue
  for UPDATE
  using (
    auth_is_super_admin()
  )
with check (
    auth_is_super_admin()
  )
;
