-- invoices had no human-readable reference at all -- just a uuid id. The Finance > Invoices
-- table has been deriving a fake one purely for display (invoiceRef() in
-- invoices-section.tsx: 'INV-' + first 8 chars of the uuid, uppercased), which is neither
-- school-identified nor sequential/meaningful.
--
-- Adds a real invoice_number column, generated the same way as po_number/application_number:
-- a BEFORE INSERT trigger resolving each school's own application_number_prefix, in the same
-- {SCHOOL-PREFIX}-{TAG}/{YY}/{DD}/{MM}/{SEQ} shape (e.g. LBS-INV/26/17/09/001), so every
-- date-stamped document reference in the app is now visually consistent (application/PO/
-- receipt/invoice all differ only by tag).
--
-- Historical invoices (11 rows total, checked live -- pre-launch/pilot scale, no schema
-- change risk) get invoice_number = null; the frontend keeps falling back to the old
-- derived INV-{id prefix} display for any row where invoice_number is null, so nothing
-- already shown to a school/parent changes retroactively. Only invoices created from here
-- forward get a real number.
alter table public.invoices add column if not exists invoice_number text;

create or replace function public.generate_invoice_number(p_school_id uuid)
returns text
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_prefix text;
  v_year2 text := to_char(now(), 'YY');
  v_day text := to_char(now(), 'DD');
  v_month text := to_char(now(), 'MM');
  v_next int;
begin
  if auth.uid() is not null and auth_school_id() is distinct from p_school_id then
    raise exception 'not authorized for this school';
  end if;

  select application_number_prefix into v_prefix from public.schools where id = p_school_id;
  if v_prefix is null then
    raise exception 'School has no application number prefix configured.';
  end if;

  perform pg_advisory_xact_lock(hashtext(p_school_id::text || v_year2 || '-inv'));

  select coalesce(max(substring(invoice_number from '(\d+)$')::int), 0) + 1
    into v_next
    from public.invoices
    where school_id = p_school_id
      and invoice_number like v_prefix || '-INV/' || v_year2 || '/%';

  return v_prefix || '-INV/' || v_year2 || '/' || v_day || '/' || v_month || '/' || lpad(v_next::text, 3, '0');
end;
$function$;

revoke execute on function public.generate_invoice_number(uuid) from public;
revoke execute on function public.generate_invoice_number(uuid) from anon;
grant execute on function public.generate_invoice_number(uuid) to authenticated, service_role;

create or replace function public.set_invoice_number()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  if new.invoice_number is null or trim(new.invoice_number) = '' then
    new.invoice_number := public.generate_invoice_number(new.school_id);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_invoice_number on public.invoices;
create trigger trg_set_invoice_number
  before insert on public.invoices
  for each row execute function public.set_invoice_number();

comment on column public.invoices.invoice_number is
  'Auto-generated by trg_set_invoice_number/generate_invoice_number as {SCHOOL-PREFIX}-INV/{YY}/{DD}/{MM}/{SEQ} (e.g. LBS-INV/26/17/09/001). Historical invoices predating this migration have invoice_number = null; the frontend falls back to the legacy derived INV-{id prefix} display for those (see invoiceRef() in invoices-section.tsx).';
