-- NEMIS Integration (item 3 of the current build order).
--
-- Design decision (documented, same convention as Phase 5 Item 3's third-party API scope
-- note): Kenya's NEMIS/KEMIS is a Ministry-operated web portal, not a documented public API a
-- third-party school system can call directly -- there is no "POST a learner" endpoint schools
-- can integrate against today. The realistic, honest shape of "NEMIS integration" for a school
-- system in 2026 is therefore: (1) track the NEMIS-required fields per student (UPI, birth
-- certificate number, sync status) so the data is always ready and visible, (2) generate a
-- properly formatted bulk-upload batch (the same shape NEMIS's own learner-upload template
-- expects) that a registrar drags into the NEMIS portal, and (3) record what was submitted, by
-- whom, and when, so "did we report this student to NEMIS" always has an answer. If/when the
-- Ministry issues real API credentials to a school, the batch-generation function here is the
-- exact seam a direct-submit provider would plug into -- same "provider behind one factory"
-- shape as supabase/functions/_shared/sms and /_shared/email.
--
-- Every write path here is a SECURITY DEFINER function (generate_nemis_sync_batch /
-- confirm_nemis_sync_batch / reset_student_nemis_status), same convention as
-- payment_allocations/receipts -- nothing writes nemis_sync_batches or
-- nemis_sync_batch_students directly, only through a function that checks nemis.manage itself.

-- ============================================================
-- Students: NEMIS-relevant fields. upi_number already exists (Phase 1 Item 1) and IS the
-- NEMIS Unique Personal Identifier -- no new column needed for it.
-- ============================================================
alter table public.students
  add column birth_certificate_number text,
  add column nemis_sync_status text not null default 'not_submitted'
    check (nemis_sync_status in ('not_submitted', 'included_in_batch', 'confirmed_synced')),
  add column nemis_synced_at timestamptz,
  add column nemis_notes text;

comment on column public.students.birth_certificate_number is
  'Required by NEMIS learner registration; also generally useful school-wide. Nullable -- not every student has one on file yet.';
comment on column public.students.nemis_sync_status is
  'not_submitted: never included in a batch (or reset after a rejection). included_in_batch: in a generated batch not yet confirmed. confirmed_synced: registrar confirmed the Ministry actually accepted it in the NEMIS portal.';

create index idx_students_nemis_sync_status on public.students(school_id, nemis_sync_status);

-- students already has trg_audit_students (audit_row_change) from Phase 17 -- these new
-- columns are covered by that existing trigger automatically, no new trigger needed.

-- ============================================================
-- Schools: institution-level NEMIS identifiers, set once by the school (Ministry-issued,
-- not generated by EduCore).
-- ============================================================
alter table public.schools
  add column nemis_institution_code text,
  add column nemis_county text,
  add column nemis_sub_county text;

comment on column public.schools.nemis_institution_code is
  'Ministry-issued 4-character NEMIS institution code, entered once in Integrations > NEMIS. Not generated by EduCore.';

-- ============================================================
-- nemis_sync_batches: one row per "generate export" action.
-- ============================================================
create table public.nemis_sync_batches (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools(id) on delete cascade,
  batch_type text not null check (batch_type in ('new_admissions', 'full_roster')),
  generated_by uuid not null references public.school_users(id),
  generated_at timestamptz not null default now(),
  student_count integer not null,
  status text not null default 'generated' check (status in ('generated', 'confirmed')),
  confirmed_by uuid references public.school_users(id),
  confirmed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.nemis_sync_batches is
  'One row per NEMIS bulk-upload export a registrar generated. status=generated until a staff member confirms the Ministry portal actually accepted the file (NEMIS has no callback -- confirmation is manual, same "human closes the loop" pattern as term_newsletter_log). Never deleted -- the only record of what was ever reported.';

create index idx_nemis_sync_batches_school_id on public.nemis_sync_batches(school_id, generated_at desc);

create trigger trg_nemis_sync_batches_updated_at
  before update on public.nemis_sync_batches
  for each row execute function public.set_updated_at();

create trigger trg_audit_nemis_sync_batches
  after insert or update or delete on public.nemis_sync_batches
  for each row execute function public.audit_row_change();

-- ============================================================
-- nemis_sync_batch_students: junction, snapshots the identifiers as they were at batch time
-- (same snapshot convention as invoices.total_amount / payroll_records.statutory_rate_id --
-- a later correction to a student's UPI should never silently rewrite what was already
-- reported in a past batch).
-- ============================================================
create table public.nemis_sync_batch_students (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references public.nemis_sync_batches(id) on delete cascade,
  student_id uuid not null references public.students(id),
  upi_number_snapshot text,
  birth_certificate_number_snapshot text,
  created_at timestamptz not null default now(),
  unique (batch_id, student_id)
);
comment on table public.nemis_sync_batch_students is
  'Which students were in a given NEMIS batch, with their identifiers snapshotted at generation time. Written only by generate_nemis_sync_batch() -- no direct insert policy, same convention as payment_allocations.';

create index idx_nemis_sync_batch_students_batch_id on public.nemis_sync_batch_students(batch_id);
create index idx_nemis_sync_batch_students_student_id on public.nemis_sync_batch_students(student_id);

alter table public.nemis_sync_batches enable row level security;
alter table public.nemis_sync_batch_students enable row level security;

-- ============================================================
-- Permission grant: nemis.manage, default to the same tier as staff.manage (Phase 0 Step 2).
-- ============================================================
insert into public.role_permissions (role_id, school_id, permission_key, allowed)
select r.id, null, 'nemis.manage', true
from public.roles r
where r.name in ('school_owner', 'principal', 'deputy_principal')
on conflict do nothing;

-- ============================================================
-- RLS: select-only for regular users; all writes go through the functions below.
-- ============================================================
create policy nemis_sync_batches_select on public.nemis_sync_batches
for select
using (
  public.auth_is_super_admin()
  or (school_id = public.auth_school_id() and public.auth_has_permission('nemis.manage'))
);

create policy nemis_sync_batch_students_select on public.nemis_sync_batch_students
for select
using (
  public.auth_is_super_admin()
  or exists (
    select 1 from public.nemis_sync_batches b
    where b.id = nemis_sync_batch_students.batch_id
      and b.school_id = public.auth_school_id()
      and public.auth_has_permission('nemis.manage')
  )
);
-- No insert/update/delete policy on either table for regular users -- SECURITY DEFINER
-- functions below are the only write path.

-- ============================================================
-- generate_nemis_sync_batch: builds a batch from students currently not_submitted (or an
-- explicit list), snapshots their identifiers, flips their status to included_in_batch.
-- Returns the new batch id.
-- ============================================================
create or replace function public.generate_nemis_sync_batch(
  p_batch_type text,
  p_student_ids uuid[] default null,
  p_notes text default null
)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_school_id uuid;
  v_actor uuid;
  v_batch_id uuid;
  v_count integer;
  v_student_ids uuid[];
begin
  if not public.auth_has_permission('nemis.manage') then
    raise exception 'Not authorized to generate NEMIS batches.';
  end if;
  if p_batch_type not in ('new_admissions', 'full_roster') then
    raise exception 'Invalid batch type.';
  end if;

  v_school_id := public.auth_school_id();
  select su.id into v_actor from public.school_users su
    where su.auth_user_id = auth.uid() and su.status = 'active';
  if v_actor is null then
    raise exception 'No active school user for the current session.';
  end if;

  -- Eligible students: active/enrolled, in this school, not already synced. When an explicit
  -- list is given, every id must resolve inside that same eligible set -- silently dropping a
  -- student the caller asked for would be worse than rejecting the whole request.
  if p_student_ids is not null then
    if exists (
      select 1 from unnest(p_student_ids) sid
      where not exists (
        select 1 from public.students st
        where st.id = sid and st.school_id = v_school_id
          and st.status in ('enrolled', 'active')
          and st.nemis_sync_status = 'not_submitted'
      )
    ) then
      raise exception 'One or more selected students are not eligible for a NEMIS batch (wrong school, already synced, or not enrolled).';
    end if;
  end if;

  -- Resolved once into a plain array (not a temp table -- a prior version used "create
  -- temporary table ... on commit drop", but that only drops at transaction commit, not
  -- statement end, so calling this function twice in the same not-yet-committed transaction
  -- raised "relation already exists". An array has no such lifetime issue.).
  select array_agg(st.id) into v_student_ids
  from public.students st
  where st.school_id = v_school_id
    and st.status in ('enrolled', 'active')
    and st.nemis_sync_status = 'not_submitted'
    and (p_student_ids is null or st.id = any (p_student_ids));

  v_count := coalesce(array_length(v_student_ids, 1), 0);
  if v_count = 0 then
    raise exception 'No eligible students to include in a NEMIS batch.';
  end if;

  insert into public.nemis_sync_batches (school_id, batch_type, generated_by, student_count, notes)
  values (v_school_id, p_batch_type, v_actor, v_count, p_notes)
  returning id into v_batch_id;

  insert into public.nemis_sync_batch_students (batch_id, student_id, upi_number_snapshot, birth_certificate_number_snapshot)
  select v_batch_id, st.id, st.upi_number, st.birth_certificate_number
  from public.students st
  where st.id = any (v_student_ids);

  update public.students
  set nemis_sync_status = 'included_in_batch'
  where id = any (v_student_ids);

  return v_batch_id;
end;
$function$;
revoke all on function public.generate_nemis_sync_batch(text, uuid[], text) from public;
grant execute on function public.generate_nemis_sync_batch(text, uuid[], text) to authenticated;

-- ============================================================
-- confirm_nemis_sync_batch: registrar confirms the Ministry portal accepted the file.
-- ============================================================
create or replace function public.confirm_nemis_sync_batch(p_batch_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_school_id uuid;
  v_actor uuid;
begin
  if not public.auth_has_permission('nemis.manage') then
    raise exception 'Not authorized to confirm NEMIS batches.';
  end if;

  v_school_id := public.auth_school_id();
  select su.id into v_actor from public.school_users su
    where su.auth_user_id = auth.uid() and su.status = 'active';

  if not exists (
    select 1 from public.nemis_sync_batches
    where id = p_batch_id and school_id = v_school_id and status = 'generated'
  ) then
    raise exception 'Batch not found, not in this school, or already confirmed.';
  end if;

  update public.nemis_sync_batches
  set status = 'confirmed', confirmed_by = v_actor, confirmed_at = now()
  where id = p_batch_id;

  update public.students
  set nemis_sync_status = 'confirmed_synced', nemis_synced_at = now()
  where id in (select student_id from public.nemis_sync_batch_students where batch_id = p_batch_id);
end;
$function$;
revoke all on function public.confirm_nemis_sync_batch(uuid) from public;
grant execute on function public.confirm_nemis_sync_batch(uuid) to authenticated;

-- ============================================================
-- reset_student_nemis_status: the Ministry portal rejected a student (bad birth cert number,
-- duplicate UPI, etc) -- puts them back in the pending queue for the next batch, with a note
-- explaining why, instead of leaving them silently stuck at included_in_batch forever.
-- ============================================================
create or replace function public.reset_student_nemis_status(p_student_id uuid, p_notes text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_school_id uuid;
begin
  if not public.auth_has_permission('nemis.manage') then
    raise exception 'Not authorized to update NEMIS status.';
  end if;
  v_school_id := public.auth_school_id();

  if not exists (select 1 from public.students where id = p_student_id and school_id = v_school_id) then
    raise exception 'Student not found in your school.';
  end if;

  update public.students
  set nemis_sync_status = 'not_submitted', nemis_synced_at = null, nemis_notes = p_notes
  where id = p_student_id;
end;
$function$;
revoke all on function public.reset_student_nemis_status(uuid, text) from public;
grant execute on function public.reset_student_nemis_status(uuid, text) to authenticated;
