-- Follow-up to H6 (20260913122353): attempted to close the root cause at the source instead
-- of relying on per-migration discipline. Applied live and the pg_default_acl entry for
-- (role postgres, schema public, functions) is verified to no longer include anon:
--   before: {postgres=X/postgres,anon=X/postgres,authenticated=X/postgres,service_role=X/postgres}
--   after:  {postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres}
--
-- CAVEAT -- verified NOT sufficient on its own: a live smoke test after this change (create a
-- throwaway function in public via both execute_sql and apply_migration, check its actual
-- grants) still showed a bare PUBLIC EXECUTE entry on the new function, which anon inherits.
-- Ruled out as explanations: a second default-acl row for role supabase_admin (postgres can't
-- alter that one -- "permission denied to change default privileges" -- and it's scoped to
-- objects the Supabase platform itself creates, not this repo's migrations); a global
-- (schema-independent, defaclnamespace = 0) default-acl row (none exists); this project's
-- event triggers (pgrst_ddl_watch, pg_cron/pg_net/pg_graphql access grants -- all scoped to
-- their own extension schemas, none touch public schema functions generally).
--
-- What's actually granting PUBLIC execute on new public-schema functions despite this default
-- ACL entry is unresolved -- likely something in Supabase's managed platform layer outside
-- plain Postgres default-privilege semantics, not something a REVOKE from this project's own
-- connection can reach.
--
-- Keeping this migration anyway since it IS a real, verified, harmless privilege reduction on
-- that stored default-acl template -- but it should NOT be read as having closed the H6 root
-- cause. Until the real mechanism is identified, every future `create function` in public
-- still needs its own explicit `revoke execute ... from anon` (and `from public`, given the
-- observed bare-PUBLIC grant), the same way H6's seven were handled -- this is still a
-- per-migration discipline problem, not a solved one.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM anon;
