-- Part 24 of the RLS consolidation series: split the applications_write
-- (ALL) + applications_select (SELECT) pair into 4 explicit per-action
-- policies. Postgres has no "ALL except SELECT" policy type, so an ALL
-- policy always also applies to SELECT alongside a separate SELECT policy
-- -- fully resolving that overlap (not just the same-action duplicates
-- resolved in parts 1-23) requires this split rather than a plain merge.
-- INSERT/UPDATE/DELETE get the former ALL policy's expression unchanged;
-- SELECT gets the literal OR of both original expressions.
--
-- This migration reconciles the repo with what is already live in
-- production -- it was applied directly via the Supabase MCP connection
-- during the audit, the DDL below was generated by Postgres itself from
-- pg_policies (format()'d server-side) rather than hand-transcribed, to
-- eliminate transcription-error risk on these long expressions, and the
-- live policies were read back and independently confirmed to match this
-- text exactly.

drop policy if exists applications_write on public.applications;
drop policy if exists applications_select on public.applications;
drop policy if exists applications_insert on public.applications;
drop policy if exists applications_update on public.applications;
drop policy if exists applications_delete on public.applications;

create policy applications_delete on public.applications
  for DELETE
  using (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('admissions.write'::text)))
  )
;

create policy applications_insert on public.applications
  for INSERT
  with check (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('admissions.write'::text)))
  )
;

create policy applications_select on public.applications
  for SELECT
  using (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('admissions.write'::text)) OR (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('admissions.read_any'::text)) OR ((guardian_id IS NOT NULL) AND (guardian_id = ( SELECT school_users.id
   FROM school_users
  WHERE ((school_users.auth_user_id = ( SELECT auth.uid() AS uid)) AND (school_users.status = 'active'::text)))))))
  )
;

create policy applications_update on public.applications
  for UPDATE
  using (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('admissions.write'::text)))
  )
with check (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('admissions.write'::text)))
  )
;
