-- Part 25. Split roles_all_super_admin (ALL) + roles_select (SELECT) into 4
-- explicit per-action policies -- same ALL+SELECT overlap reasoning as
-- part 24. roles_select intentionally allows any authenticated user to read
-- (it is a reference/lookup table of role names, not per-tenant data), which
-- is preserved unchanged.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists roles_all_super_admin on public.roles;
drop policy if exists roles_select on public.roles;
drop policy if exists roles_insert on public.roles;
drop policy if exists roles_update on public.roles;
drop policy if exists roles_delete on public.roles;

create policy roles_delete on public.roles
  for DELETE
  using (
    auth_is_super_admin()
  )
;

create policy roles_insert on public.roles
  for INSERT
  with check (
    auth_is_super_admin()
  )
;

create policy roles_select on public.roles
  for SELECT
  using (
    (auth_is_super_admin() OR (( SELECT auth.role() AS role) = 'authenticated'::text))
  )
;

create policy roles_update on public.roles
  for UPDATE
  using (
    auth_is_super_admin()
  )
with check (
    auth_is_super_admin()
  )
;
