-- Auto-reconciled by scripts/reconcile_migration_drift.py: this version was applied directly to production without a matching git commit at the time. Content below is byte-for-byte what's recorded in supabase_migrations.schema_migrations for version 20260918072617 -- reconstructed, not rewritten.

DROP POLICY IF EXISTS "competency_indicators_write" ON public."competency_indicators";
DROP POLICY IF EXISTS "competency_indicators_select" ON public."competency_indicators";
CREATE POLICY "competency_indicators_insert" ON public."competency_indicators" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin())));
CREATE POLICY "competency_indicators_delete" ON public."competency_indicators" AS PERMISSIVE FOR DELETE TO public USING ((((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin())));
CREATE POLICY "competency_indicators_update" ON public."competency_indicators" AS PERMISSIVE FOR UPDATE TO public USING ((((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))) WITH CHECK ((((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin())));
CREATE POLICY "competency_indicators_select" ON public."competency_indicators" AS PERMISSIVE FOR SELECT TO public USING ((((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin())) OR (( SELECT auth.role() AS role) = 'authenticated' AND (((school_id IS NULL) OR ((school_id = auth_school_id()) AND auth_has_permission('academics.read'::text))))));

