-- Purchase order numbers now follow the same school-prefixed scheme as
-- application numbers (20260827120000), reusing schools.application_number_prefix
-- so the same prefix identifies the school across document types -- but with
-- a "-PO" tag right after the prefix so the two reference series are visually
-- distinct at a glance: applications are 'GHS/26/27/08/001', purchase orders
-- are 'GHS-PO/26/27/08/001'.
--
-- Replaces the plain 'PO-2026-00001' column-default sequence from
-- 20260822083939_procurement_auto_po_and_stock_sync.sql with a BEFORE INSERT
-- trigger (matching the pattern already used for admission_number in
-- 20260822100723), so it can look up each school's own prefix rather than
-- using one fixed global prefix.
--
-- Historical purchase orders keep their existing 'PO-YYYY-NNNNN' numbers --
-- this only changes numbers generated from here forward. No frontend changes
-- needed -- po_number is treated as an opaque display string everywhere in
-- the app (verified via grep).
--
-- Already applied and verified live on Supabase (alzqlvfaftwegptfbfej) before
-- this commit -- confirmed via a real insert into purchase_orders returning
-- 'GHS-PO/26/27/08/001' for Gititu High School (test row deleted after). This
-- migration just brings the repo back in sync.

create or replace function public.generate_po_number(p_school_id uuid)
returns text
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_prefix text;
  v_year2 text := to_char(now(), 'YY');
  v_day text := to_char(now(), 'DD');
  v_month text := to_char(now(), 'MM');
  v_next int;
begin
  if auth.uid() is not null and auth_school_id() is distinct from p_school_id then
    raise exception 'not authorized for this school';
  end if;

  select application_number_prefix into v_prefix from public.schools where id = p_school_id;
  if v_prefix is null then
    raise exception 'School has no application number prefix configured.';
  end if;

  -- Separate advisory-lock namespace from generate_application_number's
  -- (which hashes school_id||year alone) so the two series never contend
  -- for the same lock despite sharing a school prefix.
  perform pg_advisory_xact_lock(hashtext(p_school_id::text || v_year2 || '-po'));

  select coalesce(max(substring(po_number from '(\d+)$')::int), 0) + 1
    into v_next
    from public.purchase_orders
    where school_id = p_school_id
      and po_number like v_prefix || '-PO/' || v_year2 || '/%';

  return v_prefix || '-PO/' || v_year2 || '/' || v_day || '/' || v_month || '/' || lpad(v_next::text, 3, '0');
end;
$function$;

revoke execute on function public.generate_po_number(uuid) from public;
revoke execute on function public.generate_po_number(uuid) from anon;
grant execute on function public.generate_po_number(uuid) to authenticated, service_role;

create or replace function public.set_po_number()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  if new.po_number is null or trim(new.po_number) = '' then
    new.po_number := public.generate_po_number(new.school_id);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_po_number on public.purchase_orders;
create trigger trg_set_po_number
  before insert on public.purchase_orders
  for each row execute function public.set_po_number();

-- The old column default is superseded by the trigger above (which resolves
-- a per-school prefix; the default could only ever produce one fixed global
-- prefix). po_number stays NOT NULL -- unlike admission_number, a PO always
-- gets its number at creation, there's no "interim/unassigned" state to
-- support here.
alter table public.purchase_orders alter column po_number drop default;
drop sequence if exists public.po_number_seq;

comment on column public.purchase_orders.po_number is
  'Auto-generated by trg_set_po_number/generate_po_number as {SCHOOL-PREFIX}-PO/{YY}/{DD}/{MM}/{SEQ} (e.g. GHS-PO/26/27/08/001) -- never typed by the issuer. SEQ resets each calendar year, per school. Still a real column (not computed) so a school could override it in an edge case without a schema change.';
