-- KNEC CBA export/workflow (Phase 5 Item 5 of the current build order).
--
-- Design decision (same shape as the NEMIS integration migration, and the direct
-- architectural precedent named in the CBC/CBE/KICD/KNEC investigation report): KNEC's
-- Competency-Based Assessment portal (cba.knec.ac.ke) is a credential-gated, browser-only
-- system for direct human use -- there is no documented public API and no official upload
-- file format/template was found anywhere in that investigation (see the report, section 5
-- and the open questions list). Building a guessed format and presenting it as authoritative
-- would risk producing a file that silently doesn't import. The honest, real thing to ship
-- today is therefore the same three-part shape as NEMIS: (1) track KNEC-relevant identifiers
-- (the school's own 9-digit KNEC School Code) so the data is ready, (2) generate a clearly
-- labeled PROVISIONAL export (student / sub-strand / competency level) from the existing
-- competency_marks data that a registrar/teacher manually uploads via cba.knec.ac.ke, and
-- (3) record what was ever exported and confirmed, by whom, and when. This does NOT share a
-- table with nemis_sync_batches/nemis_sync_batch_students -- different Ministry system,
-- different (and still unconfirmed) field requirements -- per the investigation report's
-- explicit recommendation.
--
-- Grain is finer than NEMIS: NEMIS batches students, KNEC CBA assesses per (student,
-- sub-strand) within an exam/assessment window, so the export/confirm cycle here tracks
-- individual competency_marks rows, not whole students. A status column is added directly to
-- competency_marks (mirroring students.nemis_sync_status) rather than only living on the
-- batch-item join, so "has this specific sub-strand rating already been reported to KNEC" is
-- always answerable straight off the marks table.
--
-- Every write path is a SECURITY DEFINER function -- nothing writes
-- knec_cba_export_batches/knec_cba_export_batch_items directly, same convention as
-- nemis_sync_batches/payment_allocations.

-- ============================================================
-- Schools: KNEC's own institution identifier. Login to cba.knec.ac.ke is by a Ministry-issued
-- 9-digit KNEC School Code (per the investigation report) -- entered once by the school, not
-- generated by EduCore, same convention as nemis_institution_code.
-- ============================================================
alter table public.schools
  add column knec_school_code text;

comment on column public.schools.knec_school_code is
  'Ministry-issued 9-digit KNEC School Code used to log into cba.knec.ac.ke, entered once in Integrations > KNEC CBA. Not generated by EduCore, not validated as a live credential.';

-- ============================================================
-- competency_marks: per-row KNEC export status, mirroring students.nemis_sync_status.
-- ============================================================
alter table public.competency_marks
  add column knec_export_status text not null default 'not_submitted'
    check (knec_export_status in ('not_submitted', 'included_in_batch', 'confirmed_submitted')),
  add column knec_submitted_at timestamptz,
  add column knec_notes text;

comment on column public.competency_marks.knec_export_status is
  'not_submitted: never included in a KNEC CBA export (or reset after a rejection/correction). included_in_batch: in a generated export not yet confirmed. confirmed_submitted: staff confirmed the school actually uploaded it on cba.knec.ac.ke.';

-- ============================================================
-- knec_cba_export_batches: one row per "generate export" action, scoped to a single exam
-- (KNEC's SBA windows are per assessment cycle, e.g. Term 3 Grade 4/5), optionally narrowed to
-- one grade.
-- ============================================================
create table public.knec_cba_export_batches (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references public.schools(id) on delete cascade,
  exam_id uuid not null references public.exams(id),
  class_id uuid references public.classes(id),
  generated_by uuid not null references public.school_users(id),
  generated_at timestamptz not null default now(),
  student_count integer not null,
  entry_count integer not null,
  status text not null default 'generated' check (status in ('generated', 'confirmed')),
  confirmed_by uuid references public.school_users(id),
  confirmed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.knec_cba_export_batches is
  'One row per KNEC CBA export a teacher/registrar generated for a given exam/assessment window. status=generated until a staff member confirms the file was actually uploaded on cba.knec.ac.ke -- KNEC has no callback, confirmation is manual, same pattern as nemis_sync_batches. Never deleted -- the only record of what was ever reported. Format is provisional (see migration header) until KNEC publishes, or a school shares, the real upload template.';

create index idx_knec_cba_export_batches_school_id on public.knec_cba_export_batches(school_id, generated_at desc);
create index idx_knec_cba_export_batches_exam_id on public.knec_cba_export_batches(exam_id);

create trigger trg_knec_cba_export_batches_updated_at
  before update on public.knec_cba_export_batches
  for each row execute function public.set_updated_at();

create trigger trg_audit_knec_cba_export_batches
  after insert or update or delete on public.knec_cba_export_batches
  for each row execute function public.audit_row_change();

-- ============================================================
-- knec_cba_export_batch_items: junction, one row per competency_marks entry included in the
-- batch. Snapshots the band label as it was at export time (same snapshot convention as
-- nemis_sync_batch_students.upi_number_snapshot) -- a later correction to the mark should
-- never silently rewrite what was already reported in a past export.
-- ============================================================
create table public.knec_cba_export_batch_items (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references public.knec_cba_export_batches(id) on delete cascade,
  competency_mark_id uuid not null references public.competency_marks(id),
  student_id uuid not null references public.students(id),
  sub_strand_id uuid not null references public.curriculum_sub_strands(id),
  band_id uuid not null references public.grading_scale_bands(id),
  band_label_snapshot text not null,
  created_at timestamptz not null default now(),
  unique (batch_id, competency_mark_id)
);
comment on table public.knec_cba_export_batch_items is
  'Which competency_marks rows were in a given KNEC export, with the competency level label snapshotted at export time. Written only by generate_knec_cba_export_batch() -- no direct insert policy.';

create index idx_knec_cba_export_batch_items_batch_id on public.knec_cba_export_batch_items(batch_id);
create index idx_knec_cba_export_batch_items_mark_id on public.knec_cba_export_batch_items(competency_mark_id);

alter table public.knec_cba_export_batches enable row level security;
alter table public.knec_cba_export_batch_items enable row level security;

-- ============================================================
-- Permission grant: knec.manage. Default to the same tier as nemis.manage plus
-- academic_officer, since this data (unlike NEMIS's admissions identifiers) comes straight
-- out of the academics/exams module.
-- ============================================================
insert into public.role_permissions (role_id, school_id, permission_key, allowed)
select r.id, null, 'knec.manage', true
from public.roles r
where r.name in ('school_owner', 'principal', 'deputy_principal', 'academic_officer')
on conflict do nothing;

-- ============================================================
-- RLS: select-only for regular users; all writes go through the functions below.
-- ============================================================
create policy knec_cba_export_batches_select on public.knec_cba_export_batches
for select
using (
  public.auth_is_super_admin()
  or (school_id = public.auth_school_id() and public.auth_has_permission('knec.manage'))
);

create policy knec_cba_export_batch_items_select on public.knec_cba_export_batch_items
for select
using (
  public.auth_is_super_admin()
  or exists (
    select 1 from public.knec_cba_export_batches b
    where b.id = knec_cba_export_batch_items.batch_id
      and b.school_id = public.auth_school_id()
      and public.auth_has_permission('knec.manage')
  )
);
-- No insert/update/delete policy on either table for regular users -- SECURITY DEFINER
-- functions below are the only write path.

-- ============================================================
-- generate_knec_cba_export_batch: builds an export from competency_marks currently
-- not_submitted for the given exam (optionally narrowed to one grade and/or an explicit
-- student list), snapshots the band label, flips their status to included_in_batch. Returns
-- the new batch id.
-- ============================================================
create or replace function public.generate_knec_cba_export_batch(
  p_exam_id uuid,
  p_class_id uuid default null,
  p_student_ids uuid[] default null,
  p_notes text default null
)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_school_id uuid;
  v_actor uuid;
  v_batch_id uuid;
  v_student_count integer;
  v_entry_count integer;
  v_mark_ids uuid[];
begin
  if not public.auth_has_permission('knec.manage') then
    raise exception 'Not authorized to generate KNEC CBA exports.';
  end if;

  v_school_id := public.auth_school_id();
  select su.id into v_actor from public.school_users su
    where su.auth_user_id = auth.uid() and su.status = 'active';
  if v_actor is null then
    raise exception 'No active school user for the current session.';
  end if;

  if not exists (select 1 from public.exams where id = p_exam_id and school_id = v_school_id) then
    raise exception 'Exam not found in your school.';
  end if;

  if p_class_id is not null and not exists (
    select 1 from public.exam_classes ec where ec.exam_id = p_exam_id and ec.class_id = p_class_id
  ) then
    raise exception 'That grade is not part of the selected exam.';
  end if;

  -- Eligible marks: this school, this exam, optional grade filter, not already exported. When
  -- an explicit student list is given, every id must have at least one eligible mark --
  -- silently dropping a student the caller asked for would be worse than rejecting the whole
  -- request (same convention as generate_nemis_sync_batch).
  if p_student_ids is not null then
    if exists (
      select 1 from unnest(p_student_ids) sid
      where not exists (
        select 1 from public.competency_marks cm
        where cm.student_id = sid
          and cm.school_id = v_school_id
          and cm.exam_id = p_exam_id
          and cm.knec_export_status = 'not_submitted'
          and (p_class_id is null or cm.class_id = p_class_id)
      )
    ) then
      raise exception 'One or more selected students have no eligible KNEC competency marks for this exam.';
    end if;
  end if;

  select array_agg(cm.id) into v_mark_ids
  from public.competency_marks cm
  where cm.school_id = v_school_id
    and cm.exam_id = p_exam_id
    and cm.knec_export_status = 'not_submitted'
    and (p_class_id is null or cm.class_id = p_class_id)
    and (p_student_ids is null or cm.student_id = any (p_student_ids));

  v_entry_count := coalesce(array_length(v_mark_ids, 1), 0);
  if v_entry_count = 0 then
    raise exception 'No eligible competency marks to export for this selection.';
  end if;

  select count(distinct cm.student_id) into v_student_count
  from public.competency_marks cm
  where cm.id = any (v_mark_ids);

  insert into public.knec_cba_export_batches
    (school_id, exam_id, class_id, generated_by, student_count, entry_count, notes)
  values (v_school_id, p_exam_id, p_class_id, v_actor, v_student_count, v_entry_count, p_notes)
  returning id into v_batch_id;

  insert into public.knec_cba_export_batch_items
    (batch_id, competency_mark_id, student_id, sub_strand_id, band_id, band_label_snapshot)
  select v_batch_id, cm.id, cm.student_id, cm.sub_strand_id, cm.band_id, gsb.label
  from public.competency_marks cm
  join public.grading_scale_bands gsb on gsb.id = cm.band_id
  where cm.id = any (v_mark_ids);

  update public.competency_marks
  set knec_export_status = 'included_in_batch'
  where id = any (v_mark_ids);

  return v_batch_id;
end;
$function$;
revoke all on function public.generate_knec_cba_export_batch(uuid, uuid, uuid[], text) from public;
grant execute on function public.generate_knec_cba_export_batch(uuid, uuid, uuid[], text) to authenticated;

-- ============================================================
-- confirm_knec_cba_export_batch: staff confirms the file was actually uploaded on
-- cba.knec.ac.ke.
-- ============================================================
create or replace function public.confirm_knec_cba_export_batch(p_batch_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_school_id uuid;
  v_actor uuid;
begin
  if not public.auth_has_permission('knec.manage') then
    raise exception 'Not authorized to confirm KNEC CBA exports.';
  end if;

  v_school_id := public.auth_school_id();
  select su.id into v_actor from public.school_users su
    where su.auth_user_id = auth.uid() and su.status = 'active';

  if not exists (
    select 1 from public.knec_cba_export_batches
    where id = p_batch_id and school_id = v_school_id and status = 'generated'
  ) then
    raise exception 'Export not found, not in this school, or already confirmed.';
  end if;

  update public.knec_cba_export_batches
  set status = 'confirmed', confirmed_by = v_actor, confirmed_at = now()
  where id = p_batch_id;

  update public.competency_marks
  set knec_export_status = 'confirmed_submitted', knec_submitted_at = now()
  where id in (
    select competency_mark_id from public.knec_cba_export_batch_items where batch_id = p_batch_id
  );
end;
$function$;
revoke all on function public.confirm_knec_cba_export_batch(uuid) from public;
grant execute on function public.confirm_knec_cba_export_batch(uuid) to authenticated;

-- ============================================================
-- reset_knec_cba_export_item: the portal rejected/needs-correction for one specific
-- (student, sub-strand) rating -- puts just that mark back in the pending queue with a note,
-- instead of resetting the whole batch.
-- ============================================================
create or replace function public.reset_knec_cba_export_item(p_competency_mark_id uuid, p_notes text)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_school_id uuid;
begin
  if not public.auth_has_permission('knec.manage') then
    raise exception 'Not authorized to update KNEC CBA export status.';
  end if;
  v_school_id := public.auth_school_id();

  if not exists (
    select 1 from public.competency_marks where id = p_competency_mark_id and school_id = v_school_id
  ) then
    raise exception 'Competency mark not found in your school.';
  end if;

  update public.competency_marks
  set knec_export_status = 'not_submitted', knec_submitted_at = null, knec_notes = p_notes
  where id = p_competency_mark_id;
end;
$function$;
revoke all on function public.reset_knec_cba_export_item(uuid, text) from public;
grant execute on function public.reset_knec_cba_export_item(uuid, text) to authenticated;
