-- Part 32. Splits competency_marks_write (ALL, created in part 20) +
-- competency_marks_select (SELECT) into 4 explicit per-action policies,
-- resolving the residual ALL+SELECT overlap that part 20 explicitly
-- deferred.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists competency_marks_write on public.competency_marks;
drop policy if exists competency_marks_write_any on public.competency_marks;
drop policy if exists competency_marks_write_own on public.competency_marks;
drop policy if exists competency_marks_select on public.competency_marks;
drop policy if exists competency_marks_insert on public.competency_marks;
drop policy if exists competency_marks_update on public.competency_marks;
drop policy if exists competency_marks_delete on public.competency_marks;

create policy competency_marks_delete on public.competency_marks
  for DELETE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM ((students st
     JOIN curriculum_sub_strands css ON ((css.id = competency_marks.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((st.id = competency_marks.student_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;

create policy competency_marks_insert on public.competency_marks
  for INSERT
  with check (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM ((students st
     JOIN curriculum_sub_strands css ON ((css.id = competency_marks.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((st.id = competency_marks.student_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;

create policy competency_marks_select on public.competency_marks
  for SELECT
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM ((students st
     JOIN curriculum_sub_strands css ON ((css.id = competency_marks.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((st.id = competency_marks.student_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))) OR ((( SELECT auth.role() AS role) = 'authenticated'::text) AND (((school_id = auth_school_id()) AND auth_has_permission('exams.read'::text)) OR (auth_user_id_is_guardian_of(student_id) AND (EXISTS ( SELECT 1
   FROM report_cards rc
  WHERE ((rc.exam_id = competency_marks.exam_id) AND (rc.student_id = competency_marks.student_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text])))))) OR ((EXISTS ( SELECT 1
   FROM (students st
     JOIN school_users su ON ((su.id = st.school_user_id)))
  WHERE ((st.id = competency_marks.student_id) AND (su.auth_user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM report_cards rc
  WHERE ((rc.exam_id = competency_marks.exam_id) AND (rc.student_id = competency_marks.student_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text])))))))))
  )
;

create policy competency_marks_update on public.competency_marks
  for UPDATE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM ((students st
     JOIN curriculum_sub_strands css ON ((css.id = competency_marks.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((st.id = competency_marks.student_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
with check (
    (((school_id = auth_school_id()) AND auth_has_permission('marks.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('marks.write'::text) AND (EXISTS ( SELECT 1
   FROM ((students st
     JOIN curriculum_sub_strands css ON ((css.id = competency_marks.sub_strand_id)))
     JOIN curriculum_strands cst ON ((cst.id = css.strand_id)))
  WHERE ((st.id = competency_marks.student_id) AND auth_user_teaches_subject_in_stream(st.current_class_id, cst.subject_id))))))
  )
;
