-- fee_waivers / scholarships as first-class records (Gap Analysis Tier 2 #8).
-- Distinct from the existing ad-hoc `discounts` table: a waiver is a durable
-- grant (a scholarship, a bursary, a staff-child discount) that applies
-- automatically to every invoice generated while it's active, rather than a
-- one-off amount knocked off a single invoice. Auto-applies by inserting an
-- already-approved `discounts` row at invoice-generation time, traced back
-- via the new `waiver_id` column — so v_student_balances and every existing
-- Finance report keep working unchanged; this is additive, not a rewrite.
create table fee_waivers (
  id uuid primary key default gen_random_uuid(),
  school_id uuid not null references schools(id),
  student_id uuid not null references students(id),
  name text not null,
  waiver_type text not null check (waiver_type in ('scholarship','bursary','staff_discount','sibling_discount','other')),
  discount_kind text not null check (discount_kind in ('percentage','fixed_amount')),
  discount_value numeric not null check (discount_value > 0),
  starts_term_id uuid references terms(id),
  ends_term_id uuid references terms(id),
  status text not null default 'active' check (status in ('active','expired','revoked')),
  notes text,
  approved_by uuid references school_users(id),
  created_by uuid references school_users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table fee_waivers is 'Durable scholarship/bursary/staff/sibling discount grants — distinct from one-off `discounts`. discount_value is a percentage (0-100) if discount_kind=percentage, else a fixed KES amount applied per invoice.';

alter table discounts add column waiver_id uuid references fee_waivers(id);
comment on column discounts.waiver_id is 'Set when this discount row was auto-generated by an active fee_waivers grant at invoice time, rather than a one-off manual discount request.';

create index idx_fee_waivers_student on fee_waivers(student_id);
create index idx_fee_waivers_school_status on fee_waivers(school_id, status);

alter table fee_waivers enable row level security;

-- Same visibility tier as discounts: finance.read staff, plus the student's
-- own guardian/self (a family can see they hold a scholarship).
create policy fee_waivers_select on fee_waivers
  for select to authenticated
  using (
    (school_id = auth_school_id() and auth_has_permission('finance.read'))
    or auth_user_id_is_guardian_of(student_id)
    or exists (
      select 1 from students st join school_users su on su.id = st.school_user_id
      where st.id = fee_waivers.student_id and su.auth_user_id = auth.uid()
    )
  );

-- Granting a recurring waiver is a bigger commitment than a single discount,
-- so it uses the SAME tier as discount approval (principal/owner), not the
-- lower finance.write tier that only lets a bursar request a one-off.
create policy fee_waivers_manage on fee_waivers
  for all to authenticated
  using (school_id = auth_school_id() and auth_has_permission('discounts.approve'))
  with check (school_id = auth_school_id() and auth_has_permission('discounts.approve'));

create or replace function public.create_fee_waiver(
  p_student_id uuid,
  p_name text,
  p_waiver_type text,
  p_discount_kind text,
  p_discount_value numeric,
  p_starts_term_id uuid default null,
  p_ends_term_id uuid default null,
  p_notes text default null
)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_school_id uuid := auth_school_id();
  v_waiver_id uuid;
  v_caller_id uuid;
begin
  if not auth_has_permission('discounts.approve') then
    raise exception 'Not authorized to grant a fee waiver.';
  end if;

  select id into v_caller_id from school_users where auth_user_id = auth.uid() and status = 'active' limit 1;

  insert into fee_waivers (school_id, student_id, name, waiver_type, discount_kind, discount_value,
    starts_term_id, ends_term_id, notes, approved_by, created_by)
  values (v_school_id, p_student_id, p_name, p_waiver_type, p_discount_kind, p_discount_value,
    p_starts_term_id, p_ends_term_id, p_notes, v_caller_id, v_caller_id)
  returning id into v_waiver_id;

  return v_waiver_id;
end;
$$;
revoke all on function public.create_fee_waiver(uuid, text, text, text, numeric, uuid, uuid, text) from public;
grant execute on function public.create_fee_waiver(uuid, text, text, text, numeric, uuid, uuid, text) to authenticated;

create or replace function public.revoke_fee_waiver(p_waiver_id uuid)
returns void
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  if not auth_has_permission('discounts.approve') then
    raise exception 'Not authorized to revoke a fee waiver.';
  end if;

  update fee_waivers set status = 'revoked', updated_at = now()
    where id = p_waiver_id and school_id = auth_school_id();
  if not found then raise exception 'Fee waiver not found.'; end if;
end;
$$;
revoke all on function public.revoke_fee_waiver(uuid) from public;
grant execute on function public.revoke_fee_waiver(uuid) to authenticated;

-- generate_invoices(): after building each invoice as before, auto-apply
-- any active fee_waivers whose term window covers this invoice's term.
create or replace function public.generate_invoices(p_term_id uuid, p_class_id uuid default null::uuid)
 returns integer
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_school_id uuid := auth_school_id();
  v_count integer := 0;
  v_student record;
  v_structure_id uuid;
  v_total numeric;
  v_invoice_id uuid;
  v_term_start date;
  v_waiver record;
  v_waiver_amount numeric;
begin
  if not auth_has_permission('finance.write') then
    raise exception 'Not authorized to generate invoices.';
  end if;

  select start_date into v_term_start from terms where id = p_term_id;

  for v_student in
    select st.id as student_id, st.current_class_id, str.class_id
    from students st
    join streams str on str.id = st.current_class_id
    where st.school_id = v_school_id
      and st.status = 'active'
      and (p_class_id is null or str.class_id = p_class_id)
      and not exists (select 1 from invoices inv where inv.student_id = st.id and inv.term_id = p_term_id)
  loop
    select id into v_structure_id from fee_structures
      where school_id = v_school_id and term_id = p_term_id and class_id = v_student.class_id
        and boarding_type = 'day' and is_active
      limit 1;
    if v_structure_id is null then
      select id into v_structure_id from fee_structures
        where school_id = v_school_id and term_id = p_term_id and class_id is null
          and boarding_type = 'day' and is_active
        limit 1;
    end if;
    if v_structure_id is null then
      continue; -- no fee structure configured for this student's grade or school-wide default; skip, don't fail the whole batch
    end if;

    select coalesce(sum(amount), 0) into v_total from fee_items where fee_structure_id = v_structure_id;

    insert into invoices (school_id, student_id, term_id, fee_structure_id, total_amount)
    values (v_school_id, v_student.student_id, p_term_id, v_structure_id, v_total)
    returning id into v_invoice_id;

    insert into invoice_items (invoice_id, name, amount)
    select v_invoice_id, name, amount from fee_items where fee_structure_id = v_structure_id;

    -- Auto-apply every fee_waivers grant active for this student whose term
    -- window covers p_term_id, tracing each generated discount back to its
    -- waiver via waiver_id.
    for v_waiver in
      select fw.id, fw.discount_kind, fw.discount_value, fw.name
      from fee_waivers fw
      where fw.student_id = v_student.student_id
        and fw.status = 'active'
        and (fw.starts_term_id is null or exists (
          select 1 from terms t where t.id = fw.starts_term_id and t.start_date <= v_term_start))
        and (fw.ends_term_id is null or exists (
          select 1 from terms t where t.id = fw.ends_term_id and t.start_date >= v_term_start))
    loop
      v_waiver_amount := case
        when v_waiver.discount_kind = 'percentage' then round(v_total * v_waiver.discount_value / 100, 2)
        else least(v_waiver.discount_value, v_total)
      end;

      insert into discounts (school_id, student_id, invoice_id, amount, reason, status, waiver_id, approved_at)
      values (v_school_id, v_student.student_id, v_invoice_id, v_waiver_amount,
        'Auto-applied waiver: ' || v_waiver.name, 'approved', v_waiver.id, now());
    end loop;

    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$function$;
