-- Part 26. Split school_groups_all_super_admin (ALL) +
-- school_groups_select_privileged (SELECT) + school_groups_update_group_admin
-- (UPDATE) into 4 explicit per-action policies -- same ALL+SELECT overlap
-- reasoning as part 24, here with a third policy (an UPDATE-specific one)
-- also folded into the merged UPDATE policy.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists school_groups_all_super_admin on public.school_groups;
drop policy if exists school_groups_select_privileged on public.school_groups;
drop policy if exists school_groups_update_group_admin on public.school_groups;
drop policy if exists school_groups_select on public.school_groups;
drop policy if exists school_groups_insert on public.school_groups;
drop policy if exists school_groups_update on public.school_groups;
drop policy if exists school_groups_delete on public.school_groups;

create policy school_groups_delete on public.school_groups
  for DELETE
  using (
    auth_is_super_admin()
  )
;

create policy school_groups_insert on public.school_groups
  for INSERT
  with check (
    auth_is_super_admin()
  )
;

create policy school_groups_select on public.school_groups
  for SELECT
  using (
    (auth_is_super_admin() OR (auth_is_super_admin() OR ((id = auth_group_id()) AND (auth_has_permission('group.branding.write'::text) OR auth_has_permission('group.reports.read'::text)))))
  )
;

create policy school_groups_update on public.school_groups
  for UPDATE
  using (
    (auth_is_super_admin() OR ((id = auth_group_id()) AND auth_has_permission('group.branding.write'::text)))
  )
with check (
    (auth_is_super_admin() OR ((id = auth_group_id()) AND auth_has_permission('group.branding.write'::text)))
  )
;
