-- Part 33. Splits remark_bank_entries_write (ALL, created in part 21) +
-- remark_bank_entries_select (SELECT) into 4 explicit per-action policies,
-- resolving the residual ALL+SELECT overlap that part 21 explicitly
-- deferred.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists remark_bank_entries_write on public.remark_bank_entries;
drop policy if exists remark_bank_entries_school_write on public.remark_bank_entries;
drop policy if exists remark_bank_entries_super_admin_write on public.remark_bank_entries;
drop policy if exists remark_bank_entries_select on public.remark_bank_entries;
drop policy if exists remark_bank_entries_insert on public.remark_bank_entries;
drop policy if exists remark_bank_entries_update on public.remark_bank_entries;
drop policy if exists remark_bank_entries_delete on public.remark_bank_entries;

create policy remark_bank_entries_delete on public.remark_bank_entries
  for DELETE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
;

create policy remark_bank_entries_insert on public.remark_bank_entries
  for INSERT
  with check (
    (((school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
;

create policy remark_bank_entries_select on public.remark_bank_entries
  for SELECT
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()) OR ((( SELECT auth.role() AS role) = 'authenticated'::text) AND ((school_id IS NULL) OR ((school_id = auth_school_id()) AND auth_has_permission('academics.read'::text)))))
  )
;

create policy remark_bank_entries_update on public.remark_bank_entries
  for UPDATE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
with check (
    (((school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
;
