-- Part 27. Split staff_attendance_write (ALL) + staff_attendance_select
-- (SELECT) into 4 explicit per-action policies -- same ALL+SELECT overlap
-- reasoning as part 24.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists staff_attendance_write on public.staff_attendance;
drop policy if exists staff_attendance_select on public.staff_attendance;
drop policy if exists staff_attendance_insert on public.staff_attendance;
drop policy if exists staff_attendance_update on public.staff_attendance;
drop policy if exists staff_attendance_delete on public.staff_attendance;

create policy staff_attendance_delete on public.staff_attendance
  for DELETE
  using (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('staff_attendance.mark'::text)))
  )
;

create policy staff_attendance_insert on public.staff_attendance
  for INSERT
  with check (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('staff_attendance.mark'::text)))
  )
;

create policy staff_attendance_select on public.staff_attendance
  for SELECT
  using (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('staff_attendance.mark'::text)) OR (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('staff_attendance.read_any'::text)) OR (EXISTS ( SELECT 1
   FROM school_users su
  WHERE ((su.id = staff_attendance.staff_id) AND (su.auth_user_id = ( SELECT auth.uid() AS uid)))))))
  )
;

create policy staff_attendance_update on public.staff_attendance
  for UPDATE
  using (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('staff_attendance.mark'::text)))
  )
with check (
    (auth_is_super_admin() OR ((school_id = auth_school_id()) AND auth_has_permission('staff_attendance.mark'::text)))
  )
;
