-- Part 30. Splits competency_indicator_ratings_write (ALL, created in part
-- 18) + competency_indicator_ratings_select (SELECT) into 4 explicit
-- per-action policies, resolving the residual ALL+SELECT overlap that part
-- 18 explicitly deferred.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists competency_indicator_ratings_write on public.competency_indicator_ratings;
drop policy if exists competency_indicator_ratings_write_any on public.competency_indicator_ratings;
drop policy if exists competency_indicator_ratings_write_own on public.competency_indicator_ratings;
drop policy if exists competency_indicator_ratings_select on public.competency_indicator_ratings;
drop policy if exists competency_indicator_ratings_insert on public.competency_indicator_ratings;
drop policy if exists competency_indicator_ratings_update on public.competency_indicator_ratings;
drop policy if exists competency_indicator_ratings_delete on public.competency_indicator_ratings;

create policy competency_indicator_ratings_delete on public.competency_indicator_ratings
  for DELETE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write'::text) AND (EXISTS ( SELECT 1
   FROM students st
  WHERE ((st.id = competency_indicator_ratings.student_id) AND auth_user_is_class_teacher_of_stream(st.current_class_id))))))
  )
;

create policy competency_indicator_ratings_insert on public.competency_indicator_ratings
  for INSERT
  with check (
    (((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write'::text) AND (EXISTS ( SELECT 1
   FROM students st
  WHERE ((st.id = competency_indicator_ratings.student_id) AND auth_user_is_class_teacher_of_stream(st.current_class_id))))))
  )
;

create policy competency_indicator_ratings_select on public.competency_indicator_ratings
  for SELECT
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write'::text) AND (EXISTS ( SELECT 1
   FROM students st
  WHERE ((st.id = competency_indicator_ratings.student_id) AND auth_user_is_class_teacher_of_stream(st.current_class_id))))) OR (((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.read'::text)) OR (auth_user_id_is_guardian_of(student_id) AND (EXISTS ( SELECT 1
   FROM (report_cards rc
     JOIN exams e ON ((e.id = rc.exam_id)))
  WHERE ((rc.student_id = competency_indicator_ratings.student_id) AND (e.term_id = competency_indicator_ratings.term_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text])))))) OR ((EXISTS ( SELECT 1
   FROM (students st
     JOIN school_users su ON ((su.id = st.school_user_id)))
  WHERE ((st.id = competency_indicator_ratings.student_id) AND (su.auth_user_id = ( SELECT auth.uid() AS uid))))) AND (EXISTS ( SELECT 1
   FROM (report_cards rc
     JOIN exams e ON ((e.id = rc.exam_id)))
  WHERE ((rc.student_id = competency_indicator_ratings.student_id) AND (e.term_id = competency_indicator_ratings.term_id) AND (rc.comment_source = ANY (ARRAY['teacher_approved'::text, 'teacher_written'::text]))))))))
  )
;

create policy competency_indicator_ratings_update on public.competency_indicator_ratings
  for UPDATE
  using (
    (((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write'::text) AND (EXISTS ( SELECT 1
   FROM students st
  WHERE ((st.id = competency_indicator_ratings.student_id) AND auth_user_is_class_teacher_of_stream(st.current_class_id))))))
  )
with check (
    (((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write_any'::text)) OR ((school_id = auth_school_id()) AND auth_has_permission('competency_ratings.write'::text) AND (EXISTS ( SELECT 1
   FROM students st
  WHERE ((st.id = competency_indicator_ratings.student_id) AND auth_user_is_class_teacher_of_stream(st.current_class_id))))))
  )
;
