-- Part 31. Splits competency_indicators_write (ALL, created in part 19) +
-- competency_indicators_select (SELECT) into 4 explicit per-action
-- policies, resolving the residual ALL+SELECT overlap that part 19
-- explicitly deferred.
--
-- Reconciles the repo with what is already live in production; DDL
-- generated by Postgres from pg_policies and read back to confirm an exact
-- match, not hand-transcribed.

drop policy if exists competency_indicators_write on public.competency_indicators;
drop policy if exists competency_indicators_school_write on public.competency_indicators;
drop policy if exists competency_indicators_super_admin_write on public.competency_indicators;
drop policy if exists competency_indicators_select on public.competency_indicators;
drop policy if exists competency_indicators_insert on public.competency_indicators;
drop policy if exists competency_indicators_update on public.competency_indicators;
drop policy if exists competency_indicators_delete on public.competency_indicators;

create policy competency_indicators_delete on public.competency_indicators
  for DELETE
  using (
    (((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
;

create policy competency_indicators_insert on public.competency_indicators
  for INSERT
  with check (
    (((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
;

create policy competency_indicators_select on public.competency_indicators
  for SELECT
  using (
    (((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()) OR ((( SELECT auth.role() AS role) = 'authenticated'::text) AND ((school_id IS NULL) OR ((school_id = auth_school_id()) AND auth_has_permission('academics.read'::text)))))
  )
;

create policy competency_indicators_update on public.competency_indicators
  for UPDATE
  using (
    (((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
with check (
    (((type = 'school_authored'::text) AND (school_id = auth_school_id()) AND auth_has_permission('academics.write'::text)) OR ((school_id IS NULL) AND auth_is_super_admin()))
  )
;
