"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";

type ActionResult = { error: string } | { success: true };

export async function generateNemisBatch(
  batchType: "new_admissions" | "full_roster",
  studentIds: string[] | null,
  notes?: string,
): Promise<{ error: string } | { success: true; batchId: string }> {
  const supabase = await createClient();

  const { data, error } = await supabase.rpc("generate_nemis_sync_batch", {
    p_batch_type: batchType,
    p_student_ids: studentIds,
    p_notes: notes?.trim() || null,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  return { success: true as const, batchId: data as string };
}

export async function confirmNemisBatch(batchId: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("confirm_nemis_sync_batch", { p_batch_id: batchId });
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  return { success: true as const };
}

export async function resetStudentNemisStatus(studentId: string, notes: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("reset_student_nemis_status", {
    p_student_id: studentId,
    p_notes: notes.trim() || null,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  revalidatePath("/students", "layout");
  return { success: true as const };
}

// School's Ministry-issued institution code -- entered once, not generated by EduCore.
export async function updateNemisInstitutionCode(code: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { data: schoolId, error: schoolIdError } = await supabase.rpc("auth_school_id");
  if (schoolIdError || !schoolId) return { error: "Could not resolve your school." };

  const { error } = await supabase
    .from("schools")
    .update({ nemis_institution_code: code.trim() || null })
    .eq("id", schoolId);
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  return { success: true as const };
}

// Fetches the full student rows (with snapshot identifiers) for a given batch so the
// client can generate the NEMIS-format .xlsx download -- kept server-side since RLS on
// nemis_sync_batch_students only allows select, and this joins in current student data
// (class/stream) the snapshot table doesn't carry.
export interface NemisBatchExportRow {
  admission_number: string;
  upi_number: string;
  birth_certificate_number: string;
  first_name: string;
  last_name: string;
  other_names: string;
  date_of_birth: string;
  gender: string;
  class_name: string;
}

export async function getNemisBatchExportRows(
  batchId: string,
): Promise<{ error: string } | { success: true; rows: NemisBatchExportRow[] }> {
  const supabase = await createClient();

  const { data: batchStudents, error: batchError } = await supabase
    .from("nemis_sync_batch_students")
    .select("student_id, upi_number_snapshot, birth_certificate_number_snapshot")
    .eq("batch_id", batchId);
  if (batchError) return { error: batchError.message };
  if (!batchStudents || batchStudents.length === 0) return { success: true as const, rows: [] };

  const { data: students, error: studentsError } = await supabase
    .from("students")
    .select("id, admission_number, first_name, last_name, other_names, date_of_birth, gender, streams(name, classes(name))")
    .in(
      "id",
      batchStudents.map((b) => b.student_id),
    );
  if (studentsError) return { error: studentsError.message };

  const byId = new Map((students ?? []).map((s) => [s.id, s]));
  const rows: NemisBatchExportRow[] = batchStudents
    .map((b) => {
      const s = byId.get(b.student_id);
      if (!s) return null;
      const stream = s.streams as unknown as { name: string; classes: { name: string } | null } | null;
      return {
        admission_number: s.admission_number,
        upi_number: b.upi_number_snapshot ?? "",
        birth_certificate_number: b.birth_certificate_number_snapshot ?? "",
        first_name: s.first_name,
        last_name: s.last_name,
        other_names: s.other_names ?? "",
        date_of_birth: s.date_of_birth,
        gender: s.gender,
        class_name: stream ? `${stream.classes?.name ?? ""} ${stream.name}`.trim() : "",
      };
    })
    .filter((r): r is NemisBatchExportRow => r !== null);

  return { success: true as const, rows };
}
