"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { extractEdgeFunctionError } from "@/lib/edge-function-error";

type ActionResult = { error: string } | { success: true };

export async function generateNemisBatch(
  batchType: "new_admissions" | "full_roster",
  studentIds: string[] | null,
  notes?: string,
): Promise<{ error: string } | { success: true; batchId: string }> {
  const supabase = await createClient();

  const { data, error } = await supabase.rpc("generate_nemis_sync_batch", {
    p_batch_type: batchType,
    p_student_ids: studentIds,
    p_notes: notes?.trim() || null,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  return { success: true as const, batchId: data as string };
}

export async function confirmNemisBatch(batchId: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("confirm_nemis_sync_batch", { p_batch_id: batchId });
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  return { success: true as const };
}

export async function resetStudentNemisStatus(studentId: string, notes: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("reset_student_nemis_status", {
    p_student_id: studentId,
    p_notes: notes.trim() || null,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  revalidatePath("/students", "layout");
  return { success: true as const };
}

// School's Ministry-issued institution code -- entered once, not generated by EduCore.
export async function updateNemisInstitutionCode(code: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { data: schoolId, error: schoolIdError } = await supabase.rpc("auth_school_id");
  if (schoolIdError || !schoolId) return { error: "Could not resolve your school." };

  const { error } = await supabase
    .from("schools")
    .update({ nemis_institution_code: code.trim() || null })
    .eq("id", schoolId);
  if (error) return { error: error.message };

  revalidatePath("/integrations/nemis");
  return { success: true as const };
}

// School's Ministry-issued KNEC School Code -- entered once, not generated by EduCore.
export async function updateKnecSchoolCode(code: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { data: schoolId, error: schoolIdError } = await supabase.rpc("auth_school_id");
  if (schoolIdError || !schoolId) return { error: "Could not resolve your school." };

  const { error } = await supabase
    .from("schools")
    .update({ knec_school_code: code.trim() || null })
    .eq("id", schoolId);
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

// Column layout for the provisional KNEC CBA export -- routed through a SECURITY DEFINER
// function (not a direct .update on schools) because schools_update's RLS policy is gated on
// settings.branding.write, not knec.manage; see the migration's comment for details.
export async function updateKnecCbaExportColumns(
  columns: { key: string; label: string; enabled: boolean }[],
): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("update_knec_cba_export_columns", { p_columns: columns });
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

export async function generateKnecCbaExportBatch(
  examId: string,
  classId: string | null,
  studentIds: string[] | null,
  notes?: string,
): Promise<{ error: string } | { success: true; batchId: string }> {
  const supabase = await createClient();

  const { data, error } = await supabase.rpc("generate_knec_cba_export_batch", {
    p_exam_id: examId,
    p_class_id: classId,
    p_student_ids: studentIds,
    p_notes: notes?.trim() || null,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const, batchId: data as string };
}

export async function confirmKnecCbaExportBatch(batchId: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("confirm_knec_cba_export_batch", { p_batch_id: batchId });
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

export async function resetKnecCbaExportItem(competencyMarkId: string, notes: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("reset_knec_cba_export_item", {
    p_competency_mark_id: competencyMarkId,
    p_notes: notes.trim() || null,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

export async function dismissKnecCbaWindowReminder(windowId: string): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("dismiss_knec_cba_window_reminder", { p_window_id: windowId });
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

export async function setKnecCbaRemindersEnabled(enabled: boolean): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("set_knec_cba_reminders_enabled", { p_enabled: enabled });
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

// CBA assessment windows are per-school data authored by that school's own management
// (knec.manage: school_owner/principal/deputy_principal/academic_officer) -- plain table writes,
// not RPCs, same shape as updateKnecSchoolCode above. RLS (school_id = auth_school_id() and
// knec.manage) is the real authorization; auth_school_id() here is just to populate the column.
export interface CbaWindowInput {
  title: string;
  gradeLabels: string[]; // empty = applies to every grade
  opensAt: string | null; // ISO date or null
  closesAt: string; // ISO date
  notes: string | null;
  sourceUrl: string | null;
}

export async function createCbaWindow(input: CbaWindowInput): Promise<ActionResult> {
  const supabase = await createClient();
  const { data: schoolId, error: schoolIdError } = await supabase.rpc("auth_school_id");
  if (schoolIdError || !schoolId) return { error: "Could not resolve your school." };

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not signed in." };

  const { data: actor } = await supabase
    .from("school_users")
    .select("id")
    .eq("auth_user_id", user.id)
    .maybeSingle();
  if (!actor) return { error: "Could not resolve your staff account." };

  const { error } = await supabase.from("knec_cba_assessment_windows").insert({
    school_id: schoolId,
    title: input.title.trim(),
    grade_labels: input.gradeLabels.length > 0 ? input.gradeLabels : null,
    opens_at: input.opensAt,
    closes_at: input.closesAt,
    notes: input.notes?.trim() || null,
    source_url: input.sourceUrl?.trim() || null,
    created_by: actor.id,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

export async function updateCbaWindow(id: string, input: CbaWindowInput): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase
    .from("knec_cba_assessment_windows")
    .update({
      title: input.title.trim(),
      grade_labels: input.gradeLabels.length > 0 ? input.gradeLabels : null,
      opens_at: input.opensAt,
      closes_at: input.closesAt,
      notes: input.notes?.trim() || null,
      source_url: input.sourceUrl?.trim() || null,
    })
    .eq("id", id);
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

export async function setCbaWindowActive(id: string, isActive: boolean): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.from("knec_cba_assessment_windows").update({ is_active: isActive }).eq("id", id);
  if (error) return { error: error.message };

  revalidatePath("/integrations/knec");
  return { success: true as const };
}

// client can generate the KNEC-ready .xlsx download -- kept server-side since RLS on
// knec_cba_export_batch_items only allows select, and this joins in current student/subject
// data the snapshot table doesn't carry (same rationale as getNemisBatchExportRows).
export interface KnecCbaExportRow {
  upi_number: string;
  admission_number: string;
  first_name: string;
  last_name: string;
  other_names: string;
  class_name: string;
  learning_area: string;
  strand: string;
  sub_strand: string;
  competency_level: string;
}

export async function getKnecCbaExportRows(
  batchId: string,
): Promise<{ error: string } | { success: true; rows: KnecCbaExportRow[] }> {
  const supabase = await createClient();

  const { data: items, error: itemsError } = await supabase
    .from("knec_cba_export_batch_items")
    .select("student_id, sub_strand_id, band_label_snapshot")
    .eq("batch_id", batchId);
  if (itemsError) return { error: itemsError.message };
  if (!items || items.length === 0) return { success: true as const, rows: [] };

  const [{ data: students, error: studentsError }, { data: subStrands, error: subStrandsError }] = await Promise.all([
    supabase
      .from("students")
      .select("id, admission_number, first_name, last_name, other_names, upi_number, streams(name, classes(name))")
      .in(
        "id",
        Array.from(new Set(items.map((i) => i.student_id))),
      ),
    supabase
      .from("curriculum_sub_strands")
      .select("id, name, curriculum_strands(name, subjects(name))")
      .in(
        "id",
        Array.from(new Set(items.map((i) => i.sub_strand_id))),
      ),
  ]);
  if (studentsError) return { error: studentsError.message };
  if (subStrandsError) return { error: subStrandsError.message };

  const studentById = new Map((students ?? []).map((s) => [s.id, s]));
  const subStrandById = new Map((subStrands ?? []).map((s) => [s.id, s]));

  const rows: KnecCbaExportRow[] = items
    .map((i) => {
      const s = studentById.get(i.student_id);
      const ss = subStrandById.get(i.sub_strand_id);
      if (!s || !ss) return null;
      const stream = s.streams as unknown as { name: string; classes: { name: string } | null } | null;
      const strand = ss.curriculum_strands as unknown as { name: string; subjects: { name: string } | null } | null;
      return {
        upi_number: s.upi_number ?? "",
        admission_number: s.admission_number,
        first_name: s.first_name,
        last_name: s.last_name,
        other_names: s.other_names ?? "",
        class_name: stream ? `${stream.classes?.name ?? ""} ${stream.name}`.trim() : "",
        learning_area: strand?.subjects?.name ?? "",
        strand: strand?.name ?? "",
        sub_strand: ss.name,
        competency_level: i.band_label_snapshot,
      };
    })
    .filter((r): r is KnecCbaExportRow => r !== null);

  return { success: true as const, rows };
}

export async function saveMpesaCredentials(input: {
  shortcode: string;
  shortcodeType: "paybill" | "till";
  environment: "sandbox" | "production";
  consumerKey: string;
  consumerSecret: string;
  passkey: string;
}): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("set_mpesa_credentials", {
    p_shortcode: input.shortcode,
    p_shortcode_type: input.shortcodeType,
    p_environment: input.environment,
    p_consumer_key: input.consumerKey,
    p_consumer_secret: input.consumerSecret,
    p_passkey: input.passkey,
  });
  if (error) return { error: error.message };

  revalidatePath("/integrations/mpesa");
  return { success: true as const };
}

export async function setMpesaActive(active: boolean): Promise<ActionResult> {
  const supabase = await createClient();
  const { error } = await supabase.rpc("set_mpesa_active", { p_active: active });
  if (error) return { error: error.message };

  revalidatePath("/integrations/mpesa");
  return { success: true as const };
}

// Creates the pending request (real authorization + rate limiting happens inside the RPC),
// then invokes the mpesa-stk-push edge function to make the actual Daraja HTTP call. The
// edge function independently re-verifies the caller can see this specific request via RLS
// under their own JWT before doing anything -- this action doesn't hand it any elevated trust.
export async function initiateMpesaPush(input: {
  studentId: string;
  amount: number;
  phoneNumber: string;
  invoiceId?: string;
  notes?: string;
}): Promise<{ error: string } | { success: true; requestId: string }> {
  const supabase = await createClient();

  const { data: requestId, error: initError } = await supabase.rpc("initiate_mpesa_stk_request", {
    p_student_id: input.studentId,
    p_amount: input.amount,
    p_phone_number: input.phoneNumber,
    p_invoice_id: input.invoiceId ?? null,
    p_notes: input.notes?.trim() || null,
  });
  if (initError) return { error: initError.message };

  const { data: invokeData, error: invokeError } = await supabase.functions.invoke("mpesa-stk-push", {
    body: { request_id: requestId },
  });
  if (invokeError) {
    return { error: await extractEdgeFunctionError(invokeError, "Failed to send the STK push.") };
  }
  if (invokeData?.error) {
    return { error: invokeData.error as string };
  }

  revalidatePath("/integrations/mpesa");
  return { success: true as const, requestId: requestId as string };
}

export async function getMpesaRequestStatus(
  requestId: string,
): Promise<{ error: string } | { success: true; status: string; resultDesc: string | null }> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("mpesa_stk_requests")
    .select("status, result_desc")
    .eq("id", requestId)
    .maybeSingle();
  if (error || !data) return { error: error?.message ?? "Request not found." };

  return { success: true as const, status: data.status, resultDesc: data.result_desc };
}
// client can generate the NEMIS-format .xlsx download -- kept server-side since RLS on
// nemis_sync_batch_students only allows select, and this joins in current student data
// (class/stream) the snapshot table doesn't carry.
export interface NemisBatchExportRow {
  admission_number: string;
  upi_number: string;
  birth_certificate_number: string;
  first_name: string;
  last_name: string;
  other_names: string;
  date_of_birth: string;
  gender: string;
  class_name: string;
}

export async function getNemisBatchExportRows(
  batchId: string,
): Promise<{ error: string } | { success: true; rows: NemisBatchExportRow[] }> {
  const supabase = await createClient();

  const { data: batchStudents, error: batchError } = await supabase
    .from("nemis_sync_batch_students")
    .select("student_id, upi_number_snapshot, birth_certificate_number_snapshot")
    .eq("batch_id", batchId);
  if (batchError) return { error: batchError.message };
  if (!batchStudents || batchStudents.length === 0) return { success: true as const, rows: [] };

  const { data: students, error: studentsError } = await supabase
    .from("students")
    .select("id, admission_number, first_name, last_name, other_names, date_of_birth, gender, streams(name, classes(name))")
    .in(
      "id",
      batchStudents.map((b) => b.student_id),
    );
  if (studentsError) return { error: studentsError.message };

  const byId = new Map((students ?? []).map((s) => [s.id, s]));
  const rows: NemisBatchExportRow[] = batchStudents
    .map((b) => {
      const s = byId.get(b.student_id);
      if (!s) return null;
      const stream = s.streams as unknown as { name: string; classes: { name: string } | null } | null;
      return {
        admission_number: s.admission_number,
        upi_number: b.upi_number_snapshot ?? "",
        birth_certificate_number: b.birth_certificate_number_snapshot ?? "",
        first_name: s.first_name,
        last_name: s.last_name,
        other_names: s.other_names ?? "",
        date_of_birth: s.date_of_birth,
        gender: s.gender,
        class_name: stream ? `${stream.classes?.name ?? ""} ${stream.name}`.trim() : "",
      };
    })
    .filter((r): r is NemisBatchExportRow => r !== null);

  return { success: true as const, rows };
}
